### ISSUE TITLE
iOS 10+ crash in plugin version 1.1.0-pre2

### ISSUE THREAD

**Issue by alezhuk** [rotorgames/Rg.Plugins.Popup#122]
PCL Interface:
```
public class NavigationInternal : INavigationInternal
{
        public async Task ShowItemsAsync(object context)
        {
                await PopupNavigation.Instance.PushAsync(
                        new PopupItemsPage { BindingContext = context });
        }
}
```
PCL Usage:
`await navigationInternal.ShowItemsAsync(this); // (this) -> instance of VM`

PCL Popup class:
```
public partial class PopupItemsPage : Rg.Plugins.Popup.Pages.PopupPage
{
        public PopupItemsPage()
        {
            InitializeComponent();
        }
}
```

It is crashing on iOS 10+, after multiple open/close of popup.
**P.S. Opening by code, close by tapping background (and make it for multiple times)**

Please see the info:
**NSObject.get_SuperHandle ()**
/Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/Foundation/NSObject2.cs line 423
**System.ObjectDisposedException: Cannot access a disposed object. Object name: 'PopupPageRenderer'.**

**CANNOT ACCESS A DISPOSED OBJECT. OBJECT NAME: 'POPUPPAGERENDERER'.**

_NSObject.get_SuperHandle () /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/Foundation/NSObject2.cs:423

UIViewController.ViewDidLayoutSubviews () /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:1210

PopupPageRenderer.ViewDidLayoutSubviews ()

Trampolines+SDAction.Invoke (System.IntPtr block) /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/build/ios/native/ObjCRuntime/Trampolines.g.cs:10343

(wrapper native-to-managed) ObjCRuntime.Trampolines+SDAction:Invoke (intptr)

(wrapper managed-to-native) ObjCRuntime.Messaging:void_objc_msgSend_Double_IntPtr_IntPtr (intptr,intptr,double,intptr,intptr)

UIView.AnimateNotify (System.Double duration, System.Action animation, UIKit.UICompletionHandler completion) /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/build/ios/native/UIKit/UIView.g.cs:370

UIView.AnimateNotifyAsync (System.Double duration, System.Action animation) /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/build/ios/native/UIKit/UIView.g.cs:382

UIView.AnimateAsync (System.Double duration, System.Action animation) /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIView.cs:177

PopupPageRenderer+<KeyBoardDownNotification>d__19.MoveNext ()

ExceptionDispatchInfo.Throw () /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151

AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018

UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 () /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIKitSynchronizationContext.cs:24

NSAsyncActionDispatcher.Apply () /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/Foundation/NSAction.cs:163

(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)

UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIApplication.cs:79

UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIApplication.cs:63

Application.Main (System.String[] args) /Users/alezhuk/Project_X/PinPayment/PinPayment/PinPayment.iOS/Main.cs:14_

**Comment by rotorgames** [comment]
@alezhuk Thank you, I will fix it soon. You can be able to result in v1.1.0-pre3

**Comment by rotorgames** [comment]
@alezhuk P.S. Is it problem only on iOS?

**Comment by alezhuk** [comment]
@rotorgames yup, only for iOS. I was testing on Droid and no crash with the same steps.

**Comment by PiotrRomanskiPC** [comment]
I have the same issue in my project, when trying to open popup second time after closing first one. Only iOS. Any news on solving this one?

**Comment by bruzkovsky** [comment]
I think I have the same issue, here is my StackTrace:

`Failed to marshal the Objective-C object 0x110f55940 (type: Rg_Plugins_Popup_IOS_Renderers_PopupPageRenderer). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer' does not have a constructor that takes one IntPtr argument). Additional information: Selector: viewDidLayoutSubviews Method: Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer:ViewDidLayoutSubviews () `

```
(wrapper managed-to-native) ObjCRuntime.Messaging:objc_msgSend (intptr,intptr)
CATransaction.Commit ()
CADisplayLinkTicker.StartThread ()
ThreadHelper.ThreadStart_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
ThreadHelper.ThreadStart ()
```

**Comment by rotorgames** [comment]
@bruzkovsky Please try to remove this plugin using nuget and reinstall again.

**Comment by bruzkovsky** [comment]
Ok I'll try that, I'll let you know if it worked.

Am 13.06.2017 3:01 nachm. schrieb Kirill <notifications@github.com>:

@bruzkovsky<https://github.com/bruzkovsky> Please try to remove this plugin using nuget and reinstall again.

**Comment by shnaz** [comment]
@bruzkovsky did you manage to solve the problem?

**Comment by bruzkovsky** [comment]
@shnaz I made another package after wiping all bin/obj/packages folders and it since never happened again.

**Comment by gcadmes** [comment]
Where can find  v1.1.0-pre3? I don't see it in Nuget or in any available branches to download.
thanks much,

**Comment by gcadmes** [comment]
@rotorgames Do you think this bug will get fixed anytime soon? I'm only asking because I'd like to help fix it ASAP. This bug with the latest version  1.1.0 pre2 has completely stopped development for my dev team.
let me know, thank you

**Comment by Szymaniuk** [comment]
@rotorgames any update on when will v1.1.0-pre3 be available?

**Comment by rotorgames** [comment]
@alezhuk @gcadmes I'm so sorry that you had to wait my answer so long. I begin to fix this bug.

**Comment by rotorgames** [comment]
I have published v1.1.0-pre3. You can test it.

**Comment by cetso** [comment]
I am still getting this crash with 1.1.4.158-pre

I use
PopupNavigation.Instance.PushAsync
then
PopupNavigation.Instance.PopAsync

and the app crashes when trying to call PopAsync

**Comment by rotorgames** [comment]
@cetso Can you give me the stack trace of the exception? I don't understand what happens.

**Comment by yatespeter100** [comment]
@rotorgames  Using latest, 1.1.4.158-pre. Here is the stack trace I see in AppCenter but I am unable to repro this for now. But I do see users encountering it.

Xamarin Exception Stack:
System.NullReferenceException: Object reference not set to an instance of an object
  at Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.ViewDidLayoutSubviews () <0x101db4e54 + 0x0005c> in <c2bf6f1e86b84161baab0dfc470e68f9#510e478a0d8b9e3668d2cdf02e572773>:0
  at (wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr)
  at CoreAnimation.CATransaction.Commit () <0x1010f6498 + 0x00023> in <0b60c1467e7449608ac42f9c7bbfdd05#510e478a0d8b9e3668d2cdf02e572773>:0
  at Xamarin.Forms.Platform.iOS.CADisplayLinkTicker.StartThread () <0x101478e04 + 0x0002f> in <3d97176e5e4b463eb17f36e790a716e1#510e478a0d8b9e3668d2cdf02e572773>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x10086cbd8 + 0x000e3> in <b238a3153e534349ad10ed0787f2157a#510e478a0d8b9e3668d2cdf02e572773>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) <0x10086b268 + 0x00227> in <b238a3153e534349ad10ed0787f2157a#510e478a0d8b9e3668d2cdf02e572773>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x10086b1f4 + 0x0002f> in <b238a3153e534349ad10ed0787f2157a#510e478a0d8b9e3668d2cdf02e572773>:0
  at System.Threading.ThreadHelper.ThreadStart () <0x10086cd88 + 0x0002f> in <b238a3153e534349ad10ed0787f2157a#510e478a0d8b9e3668d2cdf02e572773>:0

**Comment by damien-alchemylabz** [comment]
This error occurred for me... I soon realised i was attempting to show to same PopupPage while 1 was open.
The crash error/crash was hitting appDelegate on iOS. (object reference as above)

**Comment by MdNaushad** [comment]
Still facing the same issue. The app crashes because of this.
It usually happens when SoftKeyboard is about to appear
Here is the stack trace from appcenter.

`NSObject.get_SuperHandle ()
UIViewController.ViewDidLayoutSubviews ()
PopupPageRenderer.ViewDidLayoutSubviews ()
PopupPageRenderer.KeyBoardUpNotification (Foundation.NSNotification notifi)
InternalNSNotificationHandler.Post (Foundation.NSNotification s)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)`

**Comment by rotorgames** [comment]
Can someone give exactly line of stack trace for this issue? I can't reproduce it and I made a lot of things to avoid this bug but it didn't help.

**Comment by AdelaPetrut** [comment]
I can confirm that also using the latest stable version (1.1.5.180) I can reproduce on IOS:

 Unhandled managed exception:
Object reference not set to an instance of an object (System.NullReferenceException)
  at Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.ViewDidLayoutSubviews () [0x00026] in <c2bf6f1e86b84161baab0dfc470e68f9>:0 
  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend(intptr,intptr)
  at CoreAnimation.CATransaction.Commit () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/CoreAnimation/CATransaction.g.cs:89 
  at Xamarin.Forms.Platform.iOS.CADisplayLinkTicker.StartThread () [0x0003a] in D:\agent_work\1\s\Xamarin.Forms.Platform.iOS\CADisplayLinkTicker.cs:61 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/thread.cs:68 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionC
ontext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:961 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:908 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:897 
  at System.Threading.ThreadHelper.ThreadStart () 
[0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/thread.cs:105 
The app has been terminated.

**Comment by adambarath** [comment]
Unfortunatelly it crashes on Android also:
Nuget: 1.1.5.188
```
[EXCEPTION] Cannot access a disposed object.
Object name: 'Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer'. (/Users/vsts/agent/2.147.1/work/1/s/PMA/PMA.Android/Diagnostics/LoggerAndroid.cs, OnCurrentDomainUnhandledException:52)
      at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <676d7664b4c644aebe247026c785071b>:0 
      at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <676d7664b4c644aebe247026c785071b>:0 
      at Android.Views.View.get_Context () [0x0000a] in <280aba1c4e524fb5931dec44a33b152d>:0 
      at Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer.DispatchTouchEvent (Android.Views.MotionEvent e) [0x00055] in <d927ed3c90894f1eb311e2dc2f5953ba>:0 
      at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00011] in <280aba1c4e524fb5931dec44a33b152d>:0 
      at (wrapper dynamic-method) System.Object.46(intptr,intptr,intptr)
```

**Comment by rotorgames** [comment]
Guys. Try to use the last version in development nuget please https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

I hope it will fix all issues you have.

**Comment by tomkecy** [comment]
We encountered the same issue in our Xamarin.Forms application. The app was crashing after tapping the standard Entry Xamarin field on iPhone 11 and iPod 7. Surprisingly the app was working fine on iPhone 12. 

**Stack trace:**
`  at Foundation.NSObject.get_SuperHandle () [0x00023] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:471 
  at UIKit.UIViewController.ViewDidLayoutSubviews () [0x00023] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs:1260 
  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidLayoutSubviews () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:176 
  at Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.ViewDidLayoutSubviews () [0x00000] in Z:\Documents\OpenSource\Rg.Plugins.Popup\Rg.Plugins.Popup\Platforms\Ios\Renderers\PopupPageRenderer.cs:112 
  at Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.KeyBoardUpNotification (Foundation.NSNotification notifi) [0x0000c] in Z:\Documents\OpenSource\Rg.Plugins.Popup\Rg.Plugins.Popup\Platforms\Ios\Renderers\PopupPageRenderer.cs:136 
  at Foundation.InternalNSNotificationHandler.Post (Foundation.NSNotification s) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSNotificationCenter.cs:48 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at Mobile.iOS.Application.Main (System.String[] args) [0x00001] in 

The fix was trivial:
In the App.xaml.cs constructor we changed setting MainPage from a PopupPage (referencing Rg.Plugins.Popup) to ContentPage. After this, the problem was gone. 

Hope that someone will find this useful!
