### ISSUE TITLE
Android 7.1.2 - System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by Szymaniuk** [rotorgames/Rg.Plugins.Popup#157]
I'm using *Rg.Plugins.Popup* in my Xamarin.Forms app.

Per not, I haven't much issues with Android (there are some on iOS), but today I had exception, that I'm no able to reproduce again.

However the stacktrace might be helpful to find the root cause:

`Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.Platform+DefaultRenderer'.
Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)<bd30a18775d94dc8b6263aecd1ca9077>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<bd30a18775d94dc8b6263aecd1ca9077>:0
Android.Views.View.SetBackgroundColor(Color color)<d855bac285f44dda8a0d8510b679b1e2>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.UpdateBackgroundColor()<3364a2d206a142d8a54cb7a9b77626da>:0
Xamarin.Forms.Platform.Android.VisualElementRenderer<TElement>.OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
<Module>.invoke_void_object_PropertyChangedEventArgs(object, PropertyChangedEventArgs)(wrapper delegate-invoke)
Xamarin.Forms.BindableObject.OnPropertyChanged(string propertyName)
Xamarin.Forms.Element.OnPropertyChanged(string propertyName)
Xamarin.Forms.BindableObject.ClearValue(BindableProperty property, bool checkaccess)
Xamarin.Forms.BindableObject.ClearValue(BindableProperty property)
Xamarin.Forms.Setter.UnApply(BindableObject target, bool fromStyle)
Xamarin.Forms.TriggerBase.OnConditionChanged(BindableObject bindable, bool oldValue, bool newValue)
Xamarin.Forms.BindingCondition.OnBoundPropertyChanged(BindableObject bindable, object oldValue, object newValue)
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, SetValueFlags attributes, bool silent)
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)
Xamarin.Forms.BindingExpression.ApplyCore(object sourceObject, BindableObject target, BindableProperty property, bool fromTarget)
Xamarin.Forms.BindingExpression.Apply(object sourceObject, BindableObject target, BindableProperty property)
Xamarin.Forms.Binding.Apply(object newContext, BindableObject bindObj, BindableProperty targetProperty)
Xamarin.Forms.BindableObject.ApplyBindings(bool skipBindingContext)
Xamarin.Forms.BindableObject.ApplyBindings()
Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, object value)
Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, object context)
Xamarin.Forms.Element.OnBindingContextChanged()
Xamarin.Forms.Cell.OnBindingContextChanged()
Xamarin.Forms.BindableObject.BindingContextPropertyChanged(BindableObject bindable, object oldvalue, object newvalue)
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, SetValueFlags attributes, bool silent)
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)
Xamarin.Forms.BindableObject.SetValue(BindableProperty property, object value, bool fromStyle, bool checkAccess)
Xamarin.Forms.BindableObject.SetValue(BindableProperty property, object value)
Xamarin.Forms.BindableObject.set_BindingContext(object value)
Xamarin.Forms.Internals.TemplatedItemsList<TView, TItem>.<UnhookItem>d__153.MoveNext()
Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()<d855bac285f44dda8a0d8510b679b1e2>:0
Java.Lang.Thread.RunnableImplementor.Run()<d855bac285f44dda8a0d8510b679b1e2>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<d855bac285f44dda8a0d8510b679b1e2>:0
at (wrapper dynamic-method) System.Object:a960454b-0830-44c5-ae98-58470dadd3eb (intptr,intptr)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.os.Handler.handleCallback()Handler.java:751
android.os.Handler.dispatchMessage()Handler.java:95
android.os.Looper.loop()Looper.java:154
android.app.ActivityThread.main()ActivityThread.java:6186
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:889
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:779`

**Comment by Szymaniuk** [comment]
UPDATE: Well, I see, that above HockeyApp stacktrace didn't mention anywhere about Rg.Plugins.Popup... however I'm 100% sure, that there were Rg.Plugins.Popup.Droid..something in stacktrace of Visual Studio debug, but I haven't copied it :x.

Will try to reproduce it again, but it's really hard to do this.

**Comment by Szymaniuk** [comment]
Just reproduce it again.
Here stacktrace from VS debug output:

```
08-08 14:02:42.945 I/MonoDroid(13254): System.ObjectDisposedException: Cannot access a disposed object.
08-08 14:02:42.945 I/MonoDroid(13254): Object name: 'Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer'.
08-08 14:02:42.945 I/MonoDroid(13254):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
08-08 14:02:42.945 I/MonoDroid(13254):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
08-08 14:02:42.945 I/MonoDroid(13254):   at Android.Views.View.get_Context () [0x0000a] in <d855bac285f44dda8a0d8510b679b1e2>:0 
08-08 14:02:42.945 I/MonoDroid(13254):   at Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer.DispatchTouchEvent (Android.Views.MotionEvent e) [0x00055] in <70ad45e656c241c9b5f2743c38c152f8>:0 
08-08 14:02:42.945 I/MonoDroid(13254):   at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x0000f] in <d855bac285f44dda8a0d8510b679b1e2>:0 
08-08 14:02:42.945 I/MonoDroid(13254):   at (wrapper dynamic-method) System.Object:8654b6f1-0b76-445c-a727-ec0155c20382 (intptr,intptr,intptr)
```

**Comment by rotorgames** [comment]
@Szymaniuk Hi. Tell me what version of plugin do you use? Did you try to use 1.1.0-pre2?

**Comment by Szymaniuk** [comment]
@rotorgames Yes, 1.1.0-pre2

**Comment by Szymaniuk** [comment]
Still the same using *1.1.0-pre3* + even latest pre-release of XF *2.5.0.19271-pre2*:

```
10-26 16:10:23.891 I/MonoDroid(15580): Object name: 'Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer'.
10-26 16:10:23.891 I/MonoDroid(15580):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <1d799d87381c4db5b1252825fd105b84>:0 
10-26 16:10:23.891 I/MonoDroid(15580):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <1d799d87381c4db5b1252825fd105b84>:0 
10-26 16:10:23.891 I/MonoDroid(15580):   at Android.Views.View.get_Context () [0x0000a] in <c82a099136944d8aa96281cf061cbc12>:0 
10-26 16:10:23.891 I/MonoDroid(15580):   at Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer.DispatchTouchEvent (Android.Views.MotionEvent e) [0x00055] in <fa9d9e269230470999139bd81cfb0379>:0 
10-26 16:10:23.891 I/MonoDroid(15580):   at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x0000f] in <c82a099136944d8aa96281cf061cbc12>:0 
10-26 16:10:23.891 I/MonoDroid(15580):   at (wrapper dynamic-method) System.Object:cc6be778-da22-4d46-95c6-98596d579a4c (intptr,intptr,intptr)
```

**Comment by Szymaniuk** [comment]
I've just temporarly workarounded it, by wrapping your **DispatchTouchEvent** implementation:
```
public override bool DispatchTouchEvent(MotionEvent e)
        {
            try
            {
                // Your **DispatchTouchEvent** normal implementation
            }
            catch (Exception ex)
            {
                return false;
            }
        }
```

I know, it's not a solution, but at least the whole app is not crashing.

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.

**Comment by kpespisa** [comment]
I believe I am seeing the same issue. It happens on a variety of devices and OS versions. I'm using 1.1.4.154-pre, and I didn't see this issue prior to the update (previously using 1.0.4)

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <ff59c385c496418caa679915da0cb5a1>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <ff59c385c496418caa679915da0cb5a1>:0
  at Android.Views.View.get_Context () [0x0000a] in <b72ad63c794e4736b6b75797df08ae7d>:0
  at Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer.DispatchTouchEvent (Android.Views.MotionEvent e) [0x00055] in <d927ed3c90894f1eb311e2dc2f5953ba>:0
  at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x0000f] in <b72ad63c794e4736b6b75797df08ae7d>:0
  at (wrapper dynamic-method) System.Object.d3bd19aa-c4c7-4fca-a7cc-58bc75fc8b6e(intptr,intptr,intptr)
```

**Comment by rotorgames** [comment]
@kpespisa Ok I will review it

**Comment by cetso** [comment]
@kpespisa I get exactly the same exception on Samsung devices. Google pixel and iOS devices works fine.

I get the exception when I call:
PopupNavigation.Instance.PopAsync();

plugin version: 1.1.4.168
android version: 7.0
device: samsung galaxy s6

**Comment by JKennedy24** [comment]
I am getting this error with latest version.

My popup contains an Editor control which would be focused at time of closing popup.

Which leads me to believe it must be caused by something around this line:

https://github.com/rotorgames/Rg.Plugins.Popup/blob/cf657634fe6cf50beb2a3c40c2939b869a89c647/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs#L144

**Comment by JKennedy24** [comment]
as suggested by @Szymaniuk this is a temp fix for the issue:

```
[assembly: ExportRenderer(typeof(PopupPage), typeof(MyAppPopupPageRenderer))]
namespace MyApp.Droid.CustomRenderers.Controls
{
    public class MyAppPopupPageRenderer : PopupPageRenderer
    {

        public MyAppPopupPageRenderer(Context context) : base(context)
        {

        }

        public override bool DispatchTouchEvent(MotionEvent e)
        {
            try
            {
                return base.DispatchTouchEvent(e);
            }
            catch (Exception)
            {
                return false;
            }

        }
    }
}
```

**Comment by Episodex** [comment]
I just had the same issue on Samsung Xcover 4. In the office we had three identical Xcovers and the error happend only on one of them (but every time). Turned out it was because **power saving** turned on.

Turning off power saving fixed the issue, and turning it on on device that previously worked was introducing the crash. So it's most probably something that Samsung's power saving changes, that causes the popup to be disposed too soon.

I also checked on Samsung S8 and Xcover 3. Everytime same story: works ok without power saving, crashes with it.

**Comment by ertan2002** [comment]
@Episodex  I have the same problem with Samsung Galaxy A5 and Rg.Plugins.Popup 1.1.14.168 (for now its the latest version). It was working on emulator but not on the real device. After I saw your comment, I realize that the power saving turned on and I made it off and it works..

Well I executed my code as :

Device.BeginInvokeOnMainThread(async () => await PopupNavigation.Instance.PopAsync());

and it works

**Comment by rotorgames** [comment]
I hope that I fixed it in the last version of the plugin which is available in [the development nuget](https://github.com/rotorgames/Rg.Plugins.Popup#setup) right now. All navigation is invoked in the main thread in the last release whatever how navigation has been invoked in the user's code.

I will be happy if someone can test it with the last version of the plugin >= 1.1.5.184.

Thanks.

**Comment by adambarath** [comment]
Unfortunatelly it still crashes on Android:
Nuget: 1.1.5.188

```
[EXCEPTION] Cannot access a disposed object.
Object name: 'Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer'. (/Users/vsts/agent/2.147.1/work/1/s/PMA/PMA.Android/Diagnostics/LoggerAndroid.cs, OnCurrentDomainUnhandledException:52)
      at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <676d7664b4c644aebe247026c785071b>:0 
      at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <676d7664b4c644aebe247026c785071b>:0 
      at Android.Views.View.get_Context () [0x0000a] in <280aba1c4e524fb5931dec44a33b152d>:0 
      at Rg.Plugins.Popup.Droid.Renderers.PopupPageRenderer.DispatchTouchEvent (Android.Views.MotionEvent e) [0x00055] in <d927ed3c90894f1eb311e2dc2f5953ba>:0 
      at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00011] in <280aba1c4e524fb5931dec44a33b152d>:0 
      at (wrapper dynamic-method) System.Object.46(intptr,intptr,intptr)
```

**Comment by dannykhreet** [comment]
i ge the same error 
Assembly Ref addref Rg.Plugins.Popup[0x7f776bdc80] -> System.Linq[0x7f72fd0c80]: 3
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.Platform+DefaultRenderer'.

**Comment by JKennedy24** [comment]
Should this issue be re-opened if people are still seeing it?

**Comment by rotorgames** [comment]
Can anyone give me exactly the line's number of the exception?

**Comment by rotorgames** [comment]
Ok, guys. I did some changes in Android's Renderer. Please, test the last version in Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99 and let me know about results. Thanks.

**Comment by WilliamWatterson86** [comment]
Hey - any news if the dev release fixed the issue?

**Comment by rotorgames** [comment]
@WilliamWatterson86 I didn't get any information about it. I hope it was fixed.

Closed. But don't be afraid to reopen it again if someone still has this issue.

**Comment by Druffl3** [comment]
Hi @rotorgames , I am facing the same issue. Most of the temporary solutions suggested in this thread hasn't worked for me.
My current Popup version is: 1.1.5.180.
I even tried it after upgrading to 1.1.5.188, yet the same exception.

C# System.ObjectDisposedException: Cannot access a disposed object.

Please help.

**Comment by Druffl3** [comment]
> @WilliamWatterson86 I didn't get any information about it. I hope it was fixed.
> 
> Closed. But don't be afraid to reopen it again if someone still has this issue.



> @WilliamWatterson86 I didn't get any information about it. I hope it was fixed.
> 
> Closed. But don't be afraid to reopen it again if someone still has this issue.

Hi @rotorgames , I am facing the same issue. Most of the temporary solutions suggested in this thread hasn't worked for me.
My current Popup version is: 1.1.5.180.
I even tried it after upgrading to 1.1.5.188, yet the same exception.

C# System.ObjectDisposedException: Cannot access a disposed object.

Please help.

**Comment by gsalve** [comment]
Getting the same issue : 

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Widget.PopupWindow'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <00c315a988634383b446eff646084784>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <00c315a988634383b446eff646084784>:0
  at Android.Widget.PopupWindow.set_ContentView (Android.Views.View value) [0x00027] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Widget.PopupWindow.cs:599
  at Telerik.XamarinForms.Primitives.RadPopup.ClearAndroidContext () [0x0002e] in <a8f0b2531d3a43e1af8a09974e2c1c8e>:0
  at Telerik.XamarinForms.Primitives.RadPopup.UpdatePopupContext () [0x00017] in <a8f0b2531d3a43e1af8a09974e2c1c8e>:0
  at Telerik.XamarinForms.Primitives.RadPopup.OnPlacementTargetRendererChanged () [0x00000] in <a8f0b2531d3a43e1af8a09974e2c1c8e>:0
  at Telerik.XamarinForms.Primitives.PopupBase.PlacementTarget_PropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00012] in <a8f0b2531d3a43e1af8a09974e2c1c8e>:0
  at Telerik.XamarinForms.Primitives.PopupBase+<>c.<AttachWeakEventListenerForPlacementTargetPropertyChanged>b__99_0 (Telerik.XamarinForms.Primitives.PopupBase listener, System.Object sender, System.ComponentModel.PropertyChangedEventArgs eventArgs) [0x00000] in <a8f0b2531d3a43e1af8a09974e2c1c8e>:0
  at Telerik.XamarinForms.Common.WeakEventListener`3[TListener,TEventSource,TEventArgs].OnEvent (System.Object sender, TEventArgs eventArgs) [0x00023] in <9e9b25dc0d3245a29ae02ea29570dc43>:0
  at at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:266
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:362
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:510
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:446
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0004d] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:374
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:349
  at Xamarin.Forms.Platform.Android.Platform.SetRenderer (Xamarin.Forms.VisualElement bindable, Xamarin.Forms.Platform.Android.IVisualElementRenderer value) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:376
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x000f2] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:329
  at Xamarin.Forms.Platform.Android.PageRenderer.Dispose (System.Boolean disposing) [0x00024] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs:51
  at Java.Lang.Object.Java.Interop.IJavaPeerable.Disposed () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:178
  at Java.Interop.JniRuntime+JniValueManager.DisposePeer (Java.Interop.IJavaPeerable value) [0x00038] in <00c315a988634383b446eff646084784>:0
  at Java.Lang.Object.Dispose () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:210
  at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnDestroyView () [0x0003c] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:81
  at AndroidX.Fragment.App.Fragment.n_OnDestroyView (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in D:\a\1\s\generated\androidx.fragment.fragment\obj\Release\monoandroid9.0\generated\src\AndroidX.Fragment.App.Fragment.cs:2052
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.108(intptr,intptr)
