### ISSUE TITLE
CloseWhenBackgroundIsClicked not works on Android with Xamarin.Forms 2.4.0.280

### ISSUE THREAD

**Issue by YZahringer** [rotorgames/Rg.Plugins.Popup#173]
The popup does not close when Background click on Android with Xamarin.Forms 2.4.0.280. This works with version 2.3.x.

**Comment by Johnnyrook777** [comment]
+1

**Comment by Aumnia** [comment]
I am also noticing this issue but only on Release builds after updating to XF 2.4.x but it works in Debug builds...

**Comment by Luca7993** [comment]
+ 1

**Comment by malokuS** [comment]
+1 Happens on Debug and Release

**Comment by prakash-chennupati** [comment]
+1 yes also noticing this on both debug and release with XF 2.4.x

**Comment by kostadinSpiridonov** [comment]
This problem can be fixed if the Click event in the Android renderer is changed to Touch event.

`        protected override void OnElementChanged(ElementChangedEventArgs<Page> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null)
            {
                this.Touch += OnBackgroundTouch;
            }

            if (e.OldElement != null)
            {
                this.Touch -= OnBackgroundTouch;
            }
        }
`
I hope this has helped you.

**Comment by EmilAlipiev** [comment]
@kostadinSpiridonov  can you create a PR for it? @rotorgames I think that you are quite busy but could you please push this important update for us?

**Comment by Luca7993** [comment]
I think that the proposed solution is not the right one:
The touch intercept also the events coming from a children stacklayout (for example in the UserAnimation demo, the touch is intercept also if you tap on the grey background where is written "user animation".
And also the touch event is called twice, for mousedown and for mouseup.
I still try to find a solution, because i need xamarin.forms 2.4....

**Comment by EmilAlipiev** [comment]
yes also recognized that it is not a solution for UWP desktop as well. This error occurs in every platform I guess, not only Android (Havent tested IOS yet)

**Comment by prakash-chennupati** [comment]
@rotorgames can you please let us know, when we might possibly getting a fix for this issue. currently using Nuget ver. 1.0.4

**Comment by tlhintoq** [comment]
Was told to move to version 1.1.0-pre1 to resolve a different issue.
Xamarin.Forms 2.4.0.282

I'm noticing the opposite problem. `CloseWhenBackgroundIsClicked="False"` in XAML and in C#- but the popup IS closing when the background is clicked.

I need it to NOT close when background is clicked.

**Comment by EmilAlipiev** [comment]
it looks like that this project is no longer supported. maybe somebody can make a copy and handle it on separate repository because we need to work with it further. we have live apps in the store.

**Comment by tlhintoq** [comment]
Why do you think the project is abandoned?  If you look at the [closed issues](https://github.com/rotorgames/Rg.Plugins.Popup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed), the last one was closed just 21 days ago.  That doesn't feel 'no longer supported' to me.  Maybe its just that bug fixes for one version are lower priority than finishing up a major revision that would wrap such issues - as an example.

**Comment by EmilAlipiev** [comment]
@tlhintoq closed issues can be closed by the OP and it was. you can clearly see that last commit was done 4 months ago and last answer from the creator of the project was 4 months ago as well. Creator was super quick in response time earlier. you will get a response with in 24h before June. I hope that he is doing fine but it looks like Project is abandoned.

**Comment by tlhintoq** [comment]
All good points.  That's why I asked what lead you to that conclusion.  I didn't dig as deeply as you did.  Thanks for the details.

**Comment by tlhintoq** [comment]
@rotorgames As @EmilAlipiev says "Hope you're okay".  Could you let folks know if you're still around?

**Comment by Maxima078** [comment]
+1

**Comment by andreinitescu** [comment]
We should get this useful functionality baked right in the framework. Show your support for the idea here https://forums.xamarin.com/discussion/105094/popups-with-custom-content The many replies you do there, the more attention it attracts.

**Comment by YigitCiray** [comment]
+1

**Comment by rotorgames** [comment]
Hi there. Thank you for your questions and supporting. I'm so sorry that I have not updated this library a lot of time. I will review this PR soon, and I will try to update this library soon.

**Comment by tlhintoq** [comment]
That's the best news I've heard all week!  I can go into the weekend with a smile on my face.

**Comment by EmilAlipiev** [comment]
we are glad that you doing fine :)

**Comment by Maxima078** [comment]
Nice to hear

**Comment by gcadmes** [comment]
For what it's worth, this is also happens on IPad Mini 4 running iOS 11.
XF 2.3.5.256-pre6

**Comment by rotorgames** [comment]
@gcadmes Did you try to test my the last changes e76d28da8ada296b3f00d59057c851e96bbd2b4d?

**Comment by Maxima078** [comment]
@gcadmes With the same Ipad and iOS version it works great for me. Check
your content you cannot have a layout or something catching events.

**Comment by rotorgames** [comment]
I have published v1.1.0-pre3. You can test it.

**Comment by kayjoekahmann** [comment]
Fix doesn't work. Popup is not shown and App crashes after a few time opening Popup.
Tested on Android
Popup-Plugin Version:  **v1.1.0-pre3**
Xamarin.Forms Version: **2.4.0.282**

**Comment by rotorgames** [comment]
@kayjoekahmann this is other problem. This issues has been fixed. 

Did you remove a popup page before invoking PushPopupAsync method?

**Comment by kayjoekahmann** [comment]
No i didn't pop a popup before

**Comment by rotorgames** [comment]
@kayjoekahmann You can't use one instance few times. You should do `pop` before using instance of popup page.

**Comment by kayjoekahmann** [comment]
I don't use the same instance multiple times. But the problem ist that the popup isn't shown after update to v1.1.0-pre1 an higher

**Comment by rotorgames** [comment]
@kayjoekahmann show your code

**Comment by kayjoekahmann** [comment]
XAML Code:
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             x:Class="AppBDE.pro.Pages.EmployeeIdPopupPage" >
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation
      PositionIn="Bottom"
      PositionOut="Center"
      ScaleIn="1"
      ScaleOut="0.7"
      DurationIn="700"/>
    </pages:PopupPage.Animation>
    <ScrollView
    HorizontalOptions="Center"
    VerticalOptions="Center">
        <AbsoluteLayout>
          <Frame
      x:Name="FrameContainer"
      Margin="15"
      HorizontalOptions="Center"
      BackgroundColor="White">
            <Grid >
              <Label Text="Mitarbeiter Id:" VerticalOptions="Center"
                     Grid.Row="0" Grid.Column="0"/>
              <Entry x:Name="_idEntry" Placeholder="ID" Text="{Binding EmployeeId}"
                     Grid.Row="0" Grid.Column="1"/>
              <Button Text="Bestätigen" Clicked="OnIdConfirmClicked"
                      Grid.Row="1" Grid.ColumnSpan="2" />
            </Grid>
          </Frame>
        </AbsoluteLayout>
    </ScrollView>
</pages:PopupPage>
```

C#:
```cs
using AppBDE.pro.Repositories;
using AppBDE.pro.ViewModels;
using Rg.Plugins.Popup.Extensions;
using Rg.Plugins.Popup.Pages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace AppBDE.pro.Pages
{
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class EmployeeIdPopupPage : PopupPage
	{
		public EmployeeIdViewModel Vm { get; set; }

		public EmployeeIdPopupPage(EmployeeIdViewModel vm) : this()
		{
			BindingContext = Vm = vm;
		}

		public EmployeeIdPopupPage()
		{
			if (Vm == null)
			{
				BindingContext = Vm = new EmployeeIdViewModel();
			}
			
			InitializeComponent();
		}

		protected override void OnAppearing()
		{
			base.OnAppearing();
			//if the employeID is set and it should be set then set the employeeId in the entry
			//if not then set the focus on the entry
			if (SettingsRepository.Current.ShouldEmployeeIdSaved && SettingsRepository.Current.EmployeeId != -1)
			{
				Vm.EmployeeId = SettingsRepository.Current.EmployeeId + "";
			}
			else
			{
				_idEntry.Focus();
			}
		}


		public async void OnIdConfirmClicked(object sender, EventArgs e)
		{
			SendPostTimeToVM();
			await Navigation.PopPopupAsync();
		}

		private void SendPostTimeToVM()
		{
			Vm.PostTimeAsync();
			Vm.EmployeeId = "";
		}
	}
}
```

and the call:
```cs
if (page is PopupPage p)
				{
					await Navigation.PushPopupAsync(p);
				}
```

**Comment by rotorgames** [comment]
@kayjoekahmann I can say only one. If you get this exception then you use one instance of PopupPage few times. Check your code.

**Comment by gcadmes** [comment]
@Maxima078 @rotorgames 
My apologies...
Regarding my previous comment about my iPad mini 4, the version of Rg.Plugins.Popup I'm using is still 1.04. I will try the latest patch and see if that changes anything.

**Comment by marcnegri** [comment]
Exactly the same issue. When do you plan to release the fix ?

**Comment by rotorgames** [comment]
@marcnegri What issue?

**Comment by marcnegri** [comment]
Hooo Sorry, I was speaking about this issue : The popup does not close when Background click on Android with Xamarin.Forms 2.4.0.280. This works with version 2.3.x.

**Comment by rotorgames** [comment]
@marcnegri What version of plugin do you use?

**Comment by marcnegri** [comment]
I'm using the  1.0.4 version. (btw, thank you very much for your work !!)

**Comment by rotorgames** [comment]
@marcnegri Thanks. You should update plugin to v1.1.0-pre3

**Comment by marcnegri** [comment]
I update plugin to v1.1.0-pre3, but still not working. I launch it on Debug et I notice that when I click outside the popup,  OnBackgroundClicked is not called

**Comment by rotorgames** [comment]
@marcnegri Show your xaml code.

**Comment by EmilAlipiev** [comment]
I just tested and it looks fine for me. thank you

**Comment by Aumnia** [comment]
v1.1.0-pre3 restores the tap on background closes popup functionality in my app after update to XF 2.4.0.18342  thank you @rotorgames !

BTW for others I had to "aggressively" clean my solution to ensure I was using pre3 (manually delete project bin and obj directories).

**Comment by EmilAlipiev** [comment]
Forgot to mention, I used latest pre release 2.5 version and it works for it also.

**Comment by gcadmes** [comment]
1.1.0-pre3 Works for me now too. 
I upgraded XF to 2.4.0.18342 from 2.3.5-pre6

**Comment by Maxima078** [comment]
It also works for me with last pre-release 1.1.0-pre3 and Xamarin.Forms
2.4.0.282.

Many thanks !

2017-10-24 3:07 GMT+02:00 gcadmes <notifications@github.com>:

**Comment by YZahringer** [comment]
Pre-release 1.1.0-pre3 fix the issue, tested with Xamarin.Forms 2.4.0.18342. Thank you.

**Comment by marcnegri** [comment]
Hi, I'll check it out. Obviously, it's my code.

**Comment by Maxima078** [comment]
I just noticed that with this new version, on Android popup is closed even
when we click inside the popup (tap to a label for instance). Is this
expected?

2017-10-24 10:27 GMT+02:00 Marc Negri <notifications@github.com>:

**Comment by YZahringer** [comment]
@Maxima078 I have the same issue

**Comment by rotorgames** [comment]
@Maxima078 No It isn't. What versions of Android, XF, Popup do you use?

**Comment by Maxima078** [comment]
@Kirill last pre-release 1.1.0-pre3 and Xamarin.Forms 2.4.0.282.

2017-10-25 6:50 GMT+02:00 Kirill <notifications@github.com>:

**Comment by Maxima078** [comment]
Regarding the diff https://github.com/rotorgames/Rg.Plugins.Popup/commit/e76d28da8ada296b3f00d59057c851e96bbd2b4d#diff-cb6516f5f2be354418b567b671d18c9c it seems expected since you are using the OnTuchEvent() method directly from the page. Shouldn't you use a "background layout" with a gestureRecognizer to separate touch event from background and content of the page?

**Comment by EmilAlipiev** [comment]
I tested using XF 2.5 pre version and when I tap inside popup where I have grid label etc, it doesnt close for me. only if I click transparent are which is considered background causes to pop out

**Comment by Maxima078** [comment]
@EmilAlipiev did you try both Android and iOS? This happens only in Android. Are you sure your content is not catching events (such as radiobutton or button entry etc.)? I'll try with XF 2.5 but it is not a solution since still in beta.

**Comment by marcnegri** [comment]
Hi everyone,

I had to clean my solution. And after that, it works fine ! Thanks
pre-release 1.1.0-pre3 and Xamarin.Forms
2.4.0.282.

**Comment by Maxima078** [comment]
@marcnegri Isn't your popup closing when you click inside the popup content?

**Comment by marcnegri** [comment]
@Maxima078, no i saw your issue and I tried to click every in the pop-up ( my pop-up has 2 labels) and I don't have your issue. Everything seems fine.

Do you have a complex xaml ?

**Comment by Maxima078** [comment]
It couldn't be simpler : 

    <?xml version="1.0" encoding="utf-8" ?>
    <pages:PopupPage
        xmlns="http://xamarin.com/schemas/2014/forms"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
        xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
        x:Class="Sample.ItemsPopup"
        BackgroundColor="Transparent"
        x:Name="Ppage">
        <pages:PopupPage.Animation>
            <animations:MoveAnimation
                PositionIn="Top"
                PositionOut="Top"
                EasingIn="SinOut"
                EasingOut="SinIn" />
        </pages:PopupPage.Animation>
         <StackLayout
            BackgroundColor="Green"
            VerticalOptions="Center"
            HorizontalOptions="Center"
            WidthRequest="200"
            HeightRequest="200">
            <Label
                Text=" foooooooooooo" />
            <Label
                Text=" baaaaaaaaaaar" />
            <Label
                Text=" foooooooooooo" />
            <Label
                Text=" baaaaaaaaaaar" />
        </StackLayout>
    </pages:PopupPage>

Nothing in my .xaml.cs except InitializeComponent().

**Comment by rotorgames** [comment]
@Maxima078 What version of Android? 

> @Kirill last pre-release 1.1.0-pre3 and Xamarin.Forms 2.4.0.282.

**Comment by Maxima078** [comment]
Android 7.1.1 with my OnePlus 3

**Comment by rotorgames** [comment]
@Maxima078 @YZahringer Confirmed

**Comment by rotorgames** [comment]
@Maxima078 @YZahringer I think that it is problem of Xamarin.Forms. XF doesn't invoke Click method from PageRenderer and always invokes OnTouchEvent even if a touch has tapped on children.

**Comment by mhawman** [comment]
Hi @rotorgames, I am facing a similar issue (may be the same).  I recently update Xamarin and Xamarin forms in our project to latest versions and in doing so I can no longer close popups when the background is clicked. we have verified that the property is set to true, and we have upgraded to 1.1.0-pre3 (we were on pre1 previously).

I have read about cleaning the solution and have gone through deleted bin/obj folders, cleaned the solution, open and closed visual studio to make sure files were in fact unlocked and removed.  When i use this function:

```
private void ShowPopup(PopupPage popup)
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                try
                {
                    var test = new TestPopup();
                    var instance = PopupNavigation.Instance;
                    if (instance != null)
                    {
                        if (test != null)
                        {
                            instance.PushAsync(test);
                        }
                        //PopupNavigation.Instance.PushAsync(popup);
                    }
                }
                catch (Exception ex)
                {
                    this.logger.Error("Error Showing Popup", ex);
                }
            });
        }
```

I get a null reference error from PushAsync even though our popup nor the instance is not null.  something inside push async comes back as null and I can not troubleshoot anything further on my end.

the xaml we are using:

```
<?xml version="1.0" encoding="utf-8" ?>

<pages:PopupPage x:Class="PathfinderX.Display.Popups.TestPopup"
                 xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
                 xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
                 x:Name="this"
                 BindingContext="{x:Reference this}"
                 CloseWhenBackgroundIsClicked="True">

    <!--  Animation  -->
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation DurationIn="0"
                                   DurationOut="0"
                                   EasingIn="SinOut"
                                   EasingOut="SinIn"
                                   HasBackgroundAnimation="True"
                                   PositionIn="Center"
                                   PositionOut="Center"
                                   ScaleIn="1"
                                   ScaleOut="1" />
    </pages:PopupPage.Animation>

    <!--  Content  -->

    <Grid BackgroundColor="Gray">

        <Grid.RowDefinitions>
            <RowDefinition Height="2*" />
            <RowDefinition Height="6*" />
            <RowDefinition Height="2*" />
        </Grid.RowDefinitions>

        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="2*" />
            <ColumnDefinition Width="6*" />
            <ColumnDefinition Width="2*" />
        </Grid.ColumnDefinitions>

        <Grid x:Name="ContentGrid"
              Grid.Row="1"
              Grid.Column="1"
              Padding="10"
              HorizontalOptions="Fill"
              BackgroundColor="Black"
              VerticalOptions="Fill">

            <Grid.RowDefinitions>
                <RowDefinition Height="10" />
                <RowDefinition Height="*" />
                <RowDefinition Height="*" />
                <RowDefinition Height="*" />
                <RowDefinition Height="10" />
            </Grid.RowDefinitions>

            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="10" />
                <ColumnDefinition Width="Auto" />
                <ColumnDefinition Width="10" />
                <ColumnDefinition Width="Auto" />
                <ColumnDefinition Width="10" />
            </Grid.ColumnDefinitions>

            <Label Grid.Row="2"
                   Grid.Column="3"
                   HorizontalOptions="StartAndExpand"
                   Text="I'm a Popup!"/>
        </Grid>
    </Grid>

</pages:PopupPage>
```
The code behind for the xaml is:

using Xamarin.Forms.Xaml;

```
namespace Project1.Display.Popups
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class TestPopup
    {
        public TestPopup()
        {
            InitializeComponent();
        }
        protected override bool OnBackButtonPressed()
        {
            return true;
        }
    }
}
```

**Comment by psummo** [comment]
CloseWhenBackgroundIsClicked="True" in the XAML work for me, but I have 3 Entry and popup dismiss if I click between 2 entry. It should work only when Transparent background is tapped

```
<pages:PopupPage.Animation>
        <animations:ScaleAnimation 
      PositionIn="Center"
      PositionOut="Center"
      ScaleIn="1.2"
      ScaleOut="0.8"
      DurationIn="400"
      DurationOut="300"
      EasingIn="SinOut"
      EasingOut="SinIn"
      HasBackgroundAnimation="True"/>
    </pages:PopupPage.Animation>
    <StackLayout BackgroundColor="White"  WidthRequest="100" Padding="16"  HeightRequest="200">
        <Label Text="Filtro " HorizontalTextAlignment="Center" FontSize="25"/>
        <Entry Placeholder=" partenza" HorizontalTextAlignment="Center" Margin="8"/>
            <Entry Placeholder=" destinazione" HorizontalTextAlignment="Center" Margin="8"/>
            <Entry Placeholder=" partenza" HorizontalTextAlignment="Center" Margin="8"/>
        <Button Text="Ricerca"/>
    </StackLayout>
```

**Comment by rotorgames** [comment]
@mhawman Hi. `PushAsync` is an async method. You should invoke it with `await` operator. `await instance.PushAsync(test);`

**Comment by rotorgames** [comment]
@psummo v1.1.0-pre3 has some problem with CloseWhenBackgroundIsClicked. It happens because of Xamarin.Forms 2.4.x

**Comment by RamonEastsoftware** [comment]
<StackLayout  x:Name="PopupWindow" VerticalOptions="FillAndExpand" Orientation="Vertical" HorizontalOptions="FillAndExpand"  BackgroundColor="Transparent"  Padding="20, 0, 20, 20">
	
    <StackLayout Orientation="Horizontal" BackgroundColor="Transparent" HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" HeightRequest="100" Padding="10, 20, 10, 20">
        <Image x:Name="FacebookIcon" Source="facebook_icon.png" Margin="5,5,5,5"></Image>
        <Image x:Name="InstagramIcon" Source="Instagram_icon.png" Margin="5,5,5,5"></Image>
    </StackLayout>
	
  </StackLayout>

var WindowTap = new TapGestureRecognizer();
			WindowTap.Tapped += (s, e) =>
			{
				Navigation.PopPopupAsync();
			};
			PopupWindow.GestureRecognizers.Add(WindowTap);

**Comment by YZahringer** [comment]
@rotorgames The problem with Android may be solved with something like this?
[https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/MotionEventHelper.cs](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/MotionEventHelper.cs)

[https://github.com/luberda-molinet/FFImageLoading/blob/f0bf61f2e1305c2424f045dabc6d25a509b41d3c/source/FFImageLoading.Forms.Droid/CachedImageRenderer.cs#L306](https://github.com/luberda-molinet/FFImageLoading/blob/f0bf61f2e1305c2424f045dabc6d25a509b41d3c/source/FFImageLoading.Forms.Droid/CachedImageRenderer.cs#L306)

**Comment by ChaseFlorell** [comment]
-pre3 doesn't seem to fix the bug. Is there anything else we need to be doing?

```xml
  <package id="Rg.Plugins.Popup" version="1.1.0-pre3" targetFramework="portable45-net45+win8" />
  <package id="Xamarin.Forms" version="2.4.0.38779" targetFramework="portable45-net45+win8" />
```

**Comment by rotorgames** [comment]
@ChaseFlorell You should do `RemovePage` before using an instance of PopupPage again.

**Comment by ChaseFlorell** [comment]
@rotorgames I'm not getting this error anymore, my solution is what I described in #185

**Comment by simon25608** [comment]
I had the same problem, but cleaning the project was solved.
My versions are:
pre-release 1.1.0-pre3 
Xamarin Forms 2.5.0.77107

**Comment by rotorgames** [comment]
@Maxima078 @YZahringer I have fixed your problem. BackgroundClicked will be invoked only if an user will click on a background.

**Comment by ankita-uttam** [comment]
Hi this issue is still happening in my project. I am not able to close popup on background click.. I dont think xamarin version is a problem here since I tried this plugin with simple xamarin project and it was working fine. Is this plugin dependent on any third party libraries as well? We are using some third party libraries in our project like Xlabs.

**Comment by castrojr913** [comment]
@ChaseFlorell Thanks bro. It worked running and closing the Popup Page respectively, writing:
```
1. PopupNavigation.PushAsync(_popupPage_)
2. PopupNavigation.PopAsync()
```

**Comment by JOSEJ94** [comment]
It's working in my current project I am currently using XF 2.4.0.18342 and PopUp 1.1.0-pre3.
Here is what i did:
1. When declaring my PopupPage in XAML I set  `CloseWhenBackgroundIsClicked="False"`
2. Overrode OnBackgroundClicked like this:
```c#
protected override bool OnBackgroundClicked()
 {
            PopupNavigation.Instance.PopAsync();
            return true;
        }
```
I expect this to solve your problem (as a workaround for now).
I tested it on Android(real device) and iOS (simulator).

**Comment by YZahringer** [comment]
@rotorgames Yes it's fixed, thanks!

**Comment by SantoshHappiestMinds** [comment]
i have an issue with the popup when we click on the pace button.popup opens multiple times.can you please check

**Comment by rotorgames** [comment]
@SantoshHappiestMinds If an user click on a button several times that a popup will be opened several times.

**Comment by SantoshHappiestMinds** [comment]
can we stop that by not opening many times ?

**Comment by ChaseFlorell** [comment]
You do that in your own code on the CanExecute command or similar.

**Comment by EmilAlipiev** [comment]
Or check before if any open popup in the stack

**Comment by clovs** [comment]
Same Problem on Android.
Background Click doesn't work for poping back.

**Comment by 1701413420** [comment]
Same Problem on Android.  
OnBackgroundClicked does not work.
XF 2.4.0.282
Plugins.Popup 1.0.4

**Comment by gsstudio** [comment]
Can someone tell me which version of RG works with which version of Xamarin, please? 
await PopupNavigation.Instance.PopAsync (); it doesn't close the popup, OnBackgroundClicked does not work either

**Comment by gcadmes** [comment]
When pushing the popup, set the animation argument to ‘false’. This (I think) fixes the issue with RG 1.0.4.  We fixed this a long time ago in our app, then upgraded to the latest pre-release. 

I’m using the latest XF and RG and I’m not seeing any issues when background is clicked.

**Comment by gsstudio** [comment]
Cool...   it's fixed, thanks!

**Comment by rotorgames** [comment]
Just use the last pre/beta release.
