### ISSUE TITLE
Prevent crash on Android when clicking outside to dismiss the dialog - 1.1.0-pre3

### ISSUE THREAD

**Issue by nbsoftware** [rotorgames/Rg.Plugins.Popup#185]
My app was crashing on Android (every API level I tested up to API 27).
I forked and build from the sources and was able to pinpoint the issue.
Cannot issue a PR (yet) as I also converted all the project to .NET Standard 2.0
Here is the diff patch:
``` src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs b/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs
index 54f9ee4..e12c1bb 100644
--- a/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs
+++ b/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs
@@ -151,7 +151,7 @@ namespace Rg.Plugins.Popup.Droid.Renderers
 
             _gestureDetector.OnTouchEvent(e);
 
-            if (!CurrentElement.InputTransparent)
+            if (CurrentElement != null && !CurrentElement.InputTransparent)
                 return baseValue;
 
             return false;
```

**Comment by rotorgames** [comment]
@nbsoftware Thank you. I will review it.

**Comment by ChaseFlorell** [comment]
Is this the bit that's causing that IllegalStateException?

**Comment by ChaseFlorell** [comment]
I will say that I "seem" to have solved this by never re-using a popup page.

changing 

```csharp
_myPopupPage = new Lazy<MyPopupPage>(() => new MyPopupPage{BindingContext = BindingContext});
// ...
PopupNavigation.PushAsync(_myPopupPage.Value);
```

to
```csharp
PopupNavigation.PushAsync(new MyPopupPage{BindingContext = BindingContext});
```

**Comment by rotorgames** [comment]
@ChaseFlorell Did you pop PopupPage before pushing again?

**Comment by ChaseFlorell** [comment]
yes, I never have a need to have multiple popups at once. As I said, I don't have the issue if I don't re-use the page.

**Comment by rotorgames** [comment]
@ChaseFlorell You will be able to reuse your page only if you will remove (pop) it before reusing.

**Comment by nbsoftware** [comment]
Hello,
Just to confirm, the fix in comment 1 seems to have made its way through 1.1.0-pre5 right?

**Comment by rotorgames** [comment]
@nbsoftware I don't understood you. Can you explain?

**Comment by nbsoftware** [comment]
I meant: has the proposed patch in https://github.com/rotorgames/Rg.Plugins.Popup/issues/185#issue-270978325 been integrated in version 1.1.0-pre5?
Having looked at the code it seems to be this issue is still not closed so I am asking about this issue's definitive status.
Is it fixed?

**Comment by rotorgames** [comment]
@nbsoftware You can see that I have fixed it. https://github.com/rotorgames/Rg.Plugins.Popup/blob/master/src/Rg.Plugins.Popup.Droid/Renderers/PopupPageRenderer.cs#L160

**Comment by nbsoftware** [comment]
Yes I saw it indeed.
Thanks for integrating it.
So is there another reason why this issue is still not closed?
Just asking.

**Comment by rotorgames** [comment]
@nbsoftware I'm waiting for an approve from you. I should exactly now that it has been fixed.

**Comment by nbsoftware** [comment]
From my several tests this patch has indeed fixed the issue.
You can close it.
Thanks

**Comment by rotorgames** [comment]
@nbsoftware Ok. Good luck.
