### ISSUE TITLE
NullReferenceException in Entry on second display of popup

### ISSUE THREAD

**Issue by bzburr** [rotorgames/Rg.Plugins.Popup#40]
When I have a popup with an Entry, the popup works on first display. No problem.

When displayed a second time - the app crashes with a NullReferenceException after the Entry handles focus and before the keyboard is displayed.
the call stack says the exception is coming from  SetElementSize in KeyBoardUpNotification

<img width="1210" alt="screen shot 2016-10-04 at 11 43 47 am" src="https://cloud.githubusercontent.com/assets/22606272/19060057/2a8066a4-8a28-11e6-9a3b-06d0d8c1a62b.png">
x

**Comment by rotorgames** [comment]
@bzburr Hi friend. Please write versions:

Popup, Xamarin.iOS, Xamarin.VS (or Xamarin Studio), Xamarin.Forms, Android or iOS platform version.

**Comment by zois** [comment]
Same here. I know you are super busy but instead of asking all the info, try to reproduce it. bzburr is pretty straightforward. When you have an entry in the popup, it crashes the second time you open the popup. It happens only in iOS, not in Android. I am using version 1.0.2. Thanks

**Comment by rotorgames** [comment]
@zois Hi friend. Can you send to github your solution?

**Comment by zois** [comment]
When using MVVM, e.g Prism may cause this issue with the navigation. What I did is using explicitly the popups navigation service to push and pop the popup and I have no issues anymore. Now I just need to tell the view model that opens the popup, that sth has changed, e.g. sth was selected from a list. Thanks again!

**Comment by EmilAlipiev** [comment]
how did you achieve to open popup from viewmodel? can you please share your code?

**Comment by cfaguayo** [comment]
Isn't there a solution for this issue yet?

**Comment by rotorgames** [comment]
@cfaguayo It can be fixed in the next version

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.

**Comment by KarlRanseier** [comment]
V1.1.0-Pre2 indeed fixes this problem - Thanks!

**Comment by lohitha123** [comment]
Hi all, 

this is not fixed ..

Please look at this once again,

I amusing the version v1.0.4 -- again i got the issues.



System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.iOS.PageRenderer.SetElementSize (Xamarin.Forms.Size size) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:62
  at Rg.Plugins.Popup.IOS.Renderers.PopupPageRenderer.KeyBoardUpNotification (Foundation.NSNotification notifi) [0x0003c] in <f0c2f165454f4412a2b16a9f4bf28a4f>:0
  at Foundation.InternalNSNotificationHandler.Post (Foundation.NSNotification s) [0x00000] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/Foundation/NSNotificationCenter.cs:48
  at at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIApplication.cs:63
  at Smartdocs.iOS.Application.Main (System.String[] args) [0x00001] in /Users/ravishankar/Desktop/oct5theditor/mobileapp/iOS/Main.cs:17

**Comment by rotorgames** [comment]
@lohitha123 Please try to update to v1.1.0-pre5
