### ISSUE TITLE
Rg.Plugins.Popup Compatibility with iOS 13 Beta 

### ISSUE THREAD

**Issue by nadkarninaveen** [rotorgames/Rg.Plugins.Popup#459]
Hi Team,

The application developed using Rg.Plugins.Popup is crashing at Rg.Plugins.Popup.Popup.Init(); where as it was working fine with previous iOS versions and even we have verified that the sample provided on github also crashed on the second launch of the popup(Open Popup).
Please let us know when can the support for the iOS13 Beta be available.

Environment Used :
Visual Studio : Version 8.2.2 
Xamarin Version : Xamarin.iOS Preview 4
Mac OS : macOS Mojave 10.14.5
iPad OS: iOS 13 Beta 7 
Xcode : Xcode11 Beta 5 11.0

Thanks 
Naveen M Nadkarni

**Comment by wadepowell** [comment]
We are also seeing a crash with iOS 13 that did not happen with iOS12.

The first popup page displays, then closes immediately, however the Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Count = 1.  When a call to PopAllAsync after verifying there is a PopupPage in the stack, a NullReferenceException is thrown.

**Example:**
`if (Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Count > 0)
  {
    await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAllAsync(true);
  }`

**Exception Stack Trace:**
System.NullReferenceException: Object reference not set to an instance of an object
  at Rg.Plugins.Popup.IOS.Impl.PopupPlatformIos.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x000f0] in <9cde9985cfe5453d836575ce17f47cbb>:0
  at Rg.Plugins.Popup.Services.PopupNavigationImpl.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x00028] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:134
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass10_0.<RemovePageAsync>b__0 () [0x000e2] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:115
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass15_0.<InvokeThreadSafty>b__0 () [0x00022] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:163
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.16.1.24/src/Xamarin.iOS/Foundation/NSAction.cs:178
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.16.1.24/src/Xamarin.iOS/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.16.1.24/src/Xamarin.iOS/UIKit/UIApplication.cs:65

**Comment by gpticar** [comment]
I also confirm there is problem with PopupStack on iOS 13. 
However, I find out that sometimes after page disappears, PopupNavigation.Instance.PopupStack.Count is not zero. 
That indicates that the page is probably still on the stack, but is not foreground.

**Comment by TGlev** [comment]
I can confirm this same exact issue. @wadepowell

**Comment by gpticar** [comment]
The more I am testing I am 100% positive that the pages that disappears stays on stack.

**Comment by gpticar** [comment]
Ok, I got some progress. I manage to got popup pages working without auto disappearing. I had to overwrite 2 methods in PopupPlatformIos:

public async Task AddAsync(PopupPage page)
{
     page.Parent = Xamarin.Forms.Application.Current.MainPage;

     if (!IsiOS9OrNewer)
          page.Layout(new Rectangle(0, 0, Xamarin.Forms.Application.Current.MainPage.Width, Xamarin.Forms.Application.Current.MainPage.Height));

     var nativePageRendererInstance = page.GetOrCreateRenderer();

      UIView nativePageView = nativePageRendererInstance.NativeView;

      UIApplication.SharedApplication.KeyWindow.AddSubview(nativePageView);
}

public async Task RemoveAsync(PopupPage page)
{
     var renderer = XFPlatform.GetRenderer(page);
     var viewController = renderer?.ViewController;

     await Task.Delay(50);

     page.DescendantRemoved -= HandleChildRemoved;

     if (renderer != null && viewController != null && !viewController.IsBeingDismissed)
     {
          var window = viewController.View.Window;
          await window.RootViewController.DismissViewControllerAsync(false);
          DisposeModelAndChildrenRenderers(page);
           //window.RootViewController.Dispose();
           //window.RootViewController = null;
           //page.Parent = null;
           //window.Hidden = true;
           //window.Dispose();

           if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
               UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;
      }
}

I guess there is something wrong with PopupPlatformRenderer, but I do not have too much time to investigate, because I have to hurry up my release for iOS 13.

Still testing, please let me know if it helped.

**Comment by PaoloLeva** [comment]
Same issue here with Popup disappearing but Stack Count not zero, and therefore crashing, on PopAsync() on iOS 13 released version

**Comment by alextorres50** [comment]
same issue here, on iOS 13 released version

**Comment by fleuverouge** [comment]
I guess the problem is that in PopupPlatformIos.cs, the PopupWindow doesn't have a strong reference, so it is released too soon.

**Comment by movisis** [comment]
> Ok, I got some progress. I manage to got popup pages working without auto disappearing. I had to overwrite 2 methods in PopupPlatformIos.cs:
> 
> public async Task AddAsync(PopupPage page)
> {
> page.Parent = Xamarin.Forms.Application.Current.MainPage;
> 
> ```
>  if (!IsiOS9OrNewer)
>       page.Layout(new Rectangle(0, 0, Xamarin.Forms.Application.Current.MainPage.Width, Xamarin.Forms.Application.Current.MainPage.Height));
> 
>  var nativePageRendererInstance = page.GetOrCreateRenderer();
> 
>   UIView nativePageView = nativePageRendererInstance.NativeView;
> 
>   UIApplication.SharedApplication.KeyWindow.AddSubview(nativePageView);
> ```
> 
> }
> 
> public async Task RemoveAsync(PopupPage page)
> {
> var renderer = XFPlatform.GetRenderer(page);
> var viewController = renderer?.ViewController;
> 
> ```
>  await Task.Delay(50);
> 
>  page.DescendantRemoved -= HandleChildRemoved;
> 
>  if (renderer != null && viewController != null && !viewController.IsBeingDismissed)
>  {
>       var window = viewController.View.Window;
>       await window.RootViewController.DismissViewControllerAsync(false);
>       DisposeModelAndChildrenRenderers(page);
>        //window.RootViewController.Dispose();
>        //window.RootViewController = null;
>        //page.Parent = null;
>        //window.Hidden = true;
>        //window.Dispose();
> 
>        if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
>            UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;
>   }
> ```
> 
> }
> 
> I guess there is something wrong with PopupPlatformRenderer, but I do not have too much time to investigate, because I have to hurry up my release for iOS 13.
> 
> Still testing, please let me know if it helped.

It helped. Thank you very much.
Is there someone working to updated the official project?

**Comment by mzhukovs** [comment]
Hitting same issue

**Comment by TGlev** [comment]
> Ok, I got some progress. I manage to got popup pages working without auto disappearing. I had to overwrite 2 methods in PopupPlatformIos.cs:
> 
> public async Task AddAsync(PopupPage page)
> {
> page.Parent = Xamarin.Forms.Application.Current.MainPage;
> 
> ```
>  if (!IsiOS9OrNewer)
>       page.Layout(new Rectangle(0, 0, Xamarin.Forms.Application.Current.MainPage.Width, Xamarin.Forms.Application.Current.MainPage.Height));
> 
>  var nativePageRendererInstance = page.GetOrCreateRenderer();
> 
>   UIView nativePageView = nativePageRendererInstance.NativeView;
> 
>   UIApplication.SharedApplication.KeyWindow.AddSubview(nativePageView);
> ```
> 
> }
> 
> public async Task RemoveAsync(PopupPage page)
> {
> var renderer = XFPlatform.GetRenderer(page);
> var viewController = renderer?.ViewController;
> 
> ```
>  await Task.Delay(50);
> 
>  page.DescendantRemoved -= HandleChildRemoved;
> 
>  if (renderer != null && viewController != null && !viewController.IsBeingDismissed)
>  {
>       var window = viewController.View.Window;
>       await window.RootViewController.DismissViewControllerAsync(false);
>       DisposeModelAndChildrenRenderers(page);
>        //window.RootViewController.Dispose();
>        //window.RootViewController = null;
>        //page.Parent = null;
>        //window.Hidden = true;
>        //window.Dispose();
> 
>        if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
>            UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;
>   }
> ```
> 
> }
> 
> I guess there is something wrong with PopupPlatformRenderer, but I do not have too much time to investigate, because I have to hurry up my release for iOS 13.
> 
> Still testing, please let me know if it helped.

How would you go about this? Cloning the code, replacing this and then building it to a new nuget package?
Im not super experienced in C# and Im wondering how I can override these methods in the right way.

**Comment by mzhukovs** [comment]
@TGlev yep that's how, and you'd have to add a NuGet Package Source in visual studio pointing to the local folder on your machine that has the built nuget to be able to add to your existing project

**Comment by gpticar** [comment]
@TGlev

> How would you go about this? Cloning the code, replacing this and then building it to a new nuget package?
> Im not super experienced in C# and Im wondering how I can override these methods in the right way.

You dont have to build nuget. Download source code (3 projects) and add them to your solution instead of nuget packages. Then reference appropriate Rg project from your projects, and you are good to go building your iOS project. Also, I didnt add Rg.Plugins.Popup.Droid because it is working fine on Android, so my Android project still has nuget package installed.

**Comment by JKennedy24** [comment]
> Ok, I got some progress. I manage to got popup pages working without auto disappearing. I had to overwrite 2 methods in PopupPlatformIos.cs:
> 
> public async Task AddAsync(PopupPage page)
> {
> page.Parent = Xamarin.Forms.Application.Current.MainPage;
> 
> ```
>  if (!IsiOS9OrNewer)
>       page.Layout(new Rectangle(0, 0, Xamarin.Forms.Application.Current.MainPage.Width, Xamarin.Forms.Application.Current.MainPage.Height));
> 
>  var nativePageRendererInstance = page.GetOrCreateRenderer();
> 
>   UIView nativePageView = nativePageRendererInstance.NativeView;
> 
>   UIApplication.SharedApplication.KeyWindow.AddSubview(nativePageView);
> ```
> 
> }
> 
> public async Task RemoveAsync(PopupPage page)
> {
> var renderer = XFPlatform.GetRenderer(page);
> var viewController = renderer?.ViewController;
> 
> ```
>  await Task.Delay(50);
> 
>  page.DescendantRemoved -= HandleChildRemoved;
> 
>  if (renderer != null && viewController != null && !viewController.IsBeingDismissed)
>  {
>       var window = viewController.View.Window;
>       await window.RootViewController.DismissViewControllerAsync(false);
>       DisposeModelAndChildrenRenderers(page);
>        //window.RootViewController.Dispose();
>        //window.RootViewController = null;
>        //page.Parent = null;
>        //window.Hidden = true;
>        //window.Dispose();
> 
>        if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
>            UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;
>   }
> ```
> 
> }
> 
> I guess there is something wrong with PopupPlatformRenderer, but I do not have too much time to investigate, because I have to hurry up my release for iOS 13.
> 
> Still testing, please let me know if it helped.

Is this done through a custom renderer or have you got the source code as part of your project.

Be nice to get a workaround for this as its a bit of a showstopper bug

**Comment by jvaneikeren** [comment]
This really is a show-stopper. Would anyone be willing to compile fix this as a temporary NuGet package that we could use until an official updated release is available?

**Comment by DevEddy** [comment]
I am also getting this error, does anyone have made any progress on this?

```csharp
Object reference not set to an instance of an object Stack:   at Rg.Plugins.Popup.IOS.Impl.PopupPlatformIos.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x000f0] in <a276c1803fd342738d7f4c4316f1765a>:0 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x00028] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:134 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass10_0.<RemovePageAsync>b__0 () [0x000e2] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:115 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass15_0.<InvokeThreadSafe>b__0 () [0x00025] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:165 
```

-- Eddy

**Comment by MikeC2** [comment]
I'm getting the null reference exception as well. Seems to be the window object that is null. I'm not seeing the popup disappear though - get the exception intermittently when the popup is closed.

**Comment by movisis** [comment]
I've managed to correct this error by downloading the full source code.
And changed the lines mentioned by @gpticar .
Its not the best solution, but its working fine.

**Comment by TGlev** [comment]
This has to be fixed fast as the users of my apps that are on IOS 13 are now completely unable to use my apps.

I'll apply the workaround for now :)

**Comment by jvaneikeren** [comment]
I tried downloading the source code and applying the workaround as well, but in my case, my popups have Entry boxes; with the workaround in place, as soon as I click on an Entry box and start typing, the application freezes.

**Comment by movisis** [comment]
Strange.. this behavior isn't happening here.. pay attention that the first paragraph replaces some part of the code. Isn't just adding lines.. I'm using latest stable version of vs 2019 Mac, and official Xcode release 11 (not beta).

**Comment by movisis** [comment]
`using System;
using System.Threading.Tasks;
using CoreGraphics;
using Foundation;
using Rg.Plugins.Popup.Contracts;
using Rg.Plugins.Popup.IOS.Extensions;
using Rg.Plugins.Popup.IOS.Impl;
using Rg.Plugins.Popup.IOS.Platform;
using Rg.Plugins.Popup.Pages;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;
using XFPlatform = Xamarin.Forms.Platform.iOS.Platform;

[assembly: Dependency(typeof(PopupPlatformIos))]
namespace Rg.Plugins.Popup.IOS.Impl
{
    [Preserve(AllMembers = true)]
    internal class PopupPlatformIos : IPopupPlatform
    {
        private bool IsiOS9OrNewer => UIDevice.CurrentDevice.CheckSystemVersion(9, 0);

        public event EventHandler OnInitialized
        {
            add => Popup.OnInitialized += value;
            remove => Popup.OnInitialized -= value;
        }

        public bool IsInitialized => Popup.IsInitialized;

        public bool IsSystemAnimationEnabled => true;

        public async Task AddAsync(PopupPage page)
        {
            page.Parent = Application.Current.MainPage;

            if (!IsiOS9OrNewer)
                page.Layout(new Rectangle(0, 0, Xamarin.Forms.Application.Current.MainPage.Width, Xamarin.Forms.Application.Current.MainPage.Height));

            var nativePageRendererInstance = page.GetOrCreateRenderer();

            UIView nativePageView = nativePageRendererInstance.NativeView;

            UIApplication.SharedApplication.KeyWindow.AddSubview(nativePageView);

            /*page.DescendantRemoved += HandleChildRemoved;

            if(UIApplication.SharedApplication.KeyWindow.WindowLevel == UIWindowLevel.Normal)
                UIApplication.SharedApplication.KeyWindow.WindowLevel = -1;

            var renderer = page.GetOrCreateRenderer();

            var window = new PopupWindow
            {
                BackgroundColor = Color.Transparent.ToUIColor()
            };
            window.RootViewController = new PopupPlatformRenderer(renderer);
            window.RootViewController.View.BackgroundColor = Color.Transparent.ToUIColor();
            window.WindowLevel = UIWindowLevel.Normal;
            window.MakeKeyAndVisible();

            if (!IsiOS9OrNewer)
            {
                window.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);
            }

            await window.RootViewController.PresentViewControllerAsync(renderer.ViewController, false);*/
        }

        public async Task RemoveAsync(PopupPage page)
        {
            var renderer = XFPlatform.GetRenderer(page);
            var viewController = renderer?.ViewController;

            await Task.Delay(50);

            page.DescendantRemoved -= HandleChildRemoved;

            if (renderer != null && viewController != null && !viewController.IsBeingDismissed)
            {
                /*var window = viewController.View.Window;
                await window.RootViewController.DismissViewControllerAsync(false);
                DisposeModelAndChildrenRenderers(page);
                window.RootViewController.Dispose();
                window.RootViewController = null;
                page.Parent = null;
                window.Hidden = true;
                window.Dispose();

                if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
                    UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;*/
                var window = viewController.View.Window;
                await window.RootViewController.DismissViewControllerAsync(false);
                DisposeModelAndChildrenRenderers(page);
                //window.RootViewController.Dispose();
                //window.RootViewController = null;
                //page.Parent = null;
                //window.Hidden = true;
                //window.Dispose();

                if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
                    UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;
            }
        }

        private void DisposeModelAndChildrenRenderers(VisualElement view)
        {
            IVisualElementRenderer renderer;
            foreach (VisualElement child in view.Descendants())
            {
                renderer = XFPlatform.GetRenderer(child);
                XFPlatform.SetRenderer(child, null);

                if (renderer != null)
                {
                    renderer.NativeView.RemoveFromSuperview();
                    renderer.Dispose();
                }
            }

            renderer = XFPlatform.GetRenderer(view);
            if (renderer != null)
            {
                renderer.NativeView.RemoveFromSuperview();
                renderer.Dispose();
            }
            XFPlatform.SetRenderer(view, null);
        }

        private void HandleChildRemoved(object sender, ElementEventArgs e)
        {
            var view = e.Element;
            DisposeModelAndChildrenRenderers((VisualElement) view);
        }
    }
}
`

**Comment by movisis** [comment]
that's the full code working here

**Comment by michaelstonis** [comment]
I figured out the issue. It has to do with how iOS 13 is managing the life of the `window` variable. To _resolve_ this for now, I just maintain a handle to the displayed windows, so that they do not automatically deallocated. 

There are [similar reports](https://stackoverflow.com/questions/57060606/uiwindow-not-showing-over-content-in-ios-13) from other iOS developers with extremely similar or the same issue.

Attached is a nuget package that can be hosted on a local machine or in DevOps for the meantime for local consumption.

I will send up a PR with this same resolution soon.

```using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreGraphics;
using Foundation;
using HealthKit;
using Rg.Plugins.Popup.Contracts;
using Rg.Plugins.Popup.IOS.Extensions;
using Rg.Plugins.Popup.IOS.Impl;
using Rg.Plugins.Popup.IOS.Platform;
using Rg.Plugins.Popup.Pages;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;
using XFPlatform = Xamarin.Forms.Platform.iOS.Platform;

[assembly: Dependency(typeof(PopupPlatformIos))]
namespace Rg.Plugins.Popup.IOS.Impl
{
    [Preserve(AllMembers = true)]
    internal class PopupPlatformIos : IPopupPlatform
    {
        private readonly List<UIWindow> _windows = new List<UIWindow>();

        private bool IsiOS9OrNewer => UIDevice.CurrentDevice.CheckSystemVersion(9, 0);
        private bool IsiOS13OrNewer => UIDevice.CurrentDevice.CheckSystemVersion(13, 0);

        public event EventHandler OnInitialized
        {
            add => Popup.OnInitialized += value;
            remove => Popup.OnInitialized -= value;
        }

        public bool IsInitialized => Popup.IsInitialized;

        public bool IsSystemAnimationEnabled => true;

        public async Task AddAsync(PopupPage page)
        {
            page.Parent = Application.Current.MainPage;

            page.DescendantRemoved += HandleChildRemoved;

            if(UIApplication.SharedApplication.KeyWindow.WindowLevel == UIWindowLevel.Normal)
                UIApplication.SharedApplication.KeyWindow.WindowLevel = -1;

            var renderer = page.GetOrCreateRenderer();

            var window = new PopupWindow();

            if(IsiOS13OrNewer)
            {
                _windows.Add(window);
            }

            window.BackgroundColor = Color.Transparent.ToUIColor();
            window.RootViewController = new PopupPlatformRenderer(renderer);
            window.RootViewController.View.BackgroundColor = Color.Transparent.ToUIColor();
            window.WindowLevel = UIWindowLevel.Normal;
            window.MakeKeyAndVisible();

            if (!IsiOS9OrNewer)
            {
                window.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);
            }

            await window.RootViewController.PresentViewControllerAsync(renderer.ViewController, false);
        }

        public async Task RemoveAsync(PopupPage page)
        {
            var renderer = XFPlatform.GetRenderer(page);
            var viewController = renderer?.ViewController;

            await Task.Delay(50);

            page.DescendantRemoved -= HandleChildRemoved;

            if (renderer != null && viewController != null && !viewController.IsBeingDismissed)
            {
                var window = viewController.View.Window;
                await window.RootViewController.DismissViewControllerAsync(false);
                DisposeModelAndChildrenRenderers(page);
                window.RootViewController.Dispose();
                window.RootViewController = null;
                page.Parent = null;
                window.Hidden = true;

                if(IsiOS13OrNewer && _windows.Contains(window))
                {
                    _windows.Remove(window);
                }

                window.Dispose();
                window = null;

                if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
                    UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;
            }
        }

        private void DisposeModelAndChildrenRenderers(VisualElement view)
        {
            IVisualElementRenderer renderer;
            foreach (VisualElement child in view.Descendants())
            {
                renderer = XFPlatform.GetRenderer(child);
                XFPlatform.SetRenderer(child, null);

                if (renderer != null)
                {
                    renderer.NativeView.RemoveFromSuperview();
                    renderer.Dispose();
                }
            }

            renderer = XFPlatform.GetRenderer(view);
            if (renderer != null)
            {
                renderer.NativeView.RemoveFromSuperview();
                renderer.Dispose();
            }
            XFPlatform.SetRenderer(view, null);
        }

        private void HandleChildRemoved(object sender, ElementEventArgs e)
        {
            var view = e.Element;
            DisposeModelAndChildrenRenderers((VisualElement) view);
        }
    }
}
```

[Rg.Plugins.Popup.1.1.5.189.nupkg.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/3650499/Rg.Plugins.Popup.1.1.5.189.nupkg.zip)

**Comment by JKennedy24** [comment]
@DevEddy  can you create a pull request of the fix and @rotorgames  can we get that pull request merged and released. this bug is a killer. Arguably apples fault for releasing such a breaking change

**Comment by DevEddy** [comment]
@JKennedy24 sure, credits to @michaelstonis 

https://github.com/rotorgames/Rg.Plugins.Popup/pull/466

**Comment by mzhukovs** [comment]
Even with the unofficially patched 1.1.5.189 version I am seeing strange behavior with popups on iOS, namely the self-closing problem (seems to work the first time or two, but then closes itself immediately thereafter). No longer does the app crash though. Anyone else?

**Comment by luizvnegrini** [comment]
Does anyone have any idea of the frequency of approvals? PRs have been open for more than months and have not been made or merged yet and this correction made you seem very urgent.

**Comment by gcadmes** [comment]
@michaelstonis Will this also work on iOS 12 as well as the fix you applied for iOS 13?

**Comment by michaelstonis** [comment]
@gcadmes it won't help for anything on iOS 12, as I added a specific filter here for iOS 13. This particular issue is not present on earlier versions of iOS though, so you should be good.

**Comment by gcadmes** [comment]
Thank you for the quick reply.... :-)

**Comment by CoderFan1** [comment]
I'm getting the same issue as soon as I updated to IOS 13

**Comment by mr5z** [comment]
> @JKennedy24 sure, credits to @michaelstonis
> 
> #466
> 
> PS: For now you could use the auto build beta nuget by appveyor to test this out.

Hi, can you tell how to do it?
Is it the same as installing NuPackage? If so, can I have the URL.
Thanks!

**Comment by DevEddy** [comment]
@mr5z You can use this source to test the changes made in the pr: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

It should be the version 1.1.5.214

**Comment by kamilkk** [comment]
@DevEddy Thanks for that URL, it saves me a lot of time and I confirm it works 👍

**Comment by mr5z** [comment]
@DevEddy thanks! I wonder how those people extract the URL from the zip file.
Anyway, It has been 8 months since the last commit. Maybe somebody has to fork this repo already?

**Comment by DevEddy** [comment]
Your welcome, but don't forget that the credits are going to @michaelstonis as he worte the code / fix.

@mr5z the url was published in the read me by the maintainer.

**Comment by luizvnegrini** [comment]
> @DevEddy thanks! I wonder how those people extract the URL from the zip file.
> Anyway, It has been 8 months since the last commit. Maybe somebody has to fork this repo already?

If you do, tell us or as soon as possible

**Comment by JKennedy24** [comment]
@DevEddy 

I'm using this https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99 as a packagesource now in my project.

Is this the right way to do it? the url isnt going anywhere is it?

**Comment by DevEddy** [comment]
@JKennedy24 correct, this URL is fix

**Comment by DevEddy** [comment]
@mzhukovs have you tried 1.1.5.214?

**Comment by dfarrNTST** [comment]
Is there any way to get this in the primary build for the release that is on nuget.org?

**Comment by DevEddy** [comment]
@dfarrNTST the only way is to merge this PR and create the nuget or fork and create your own nuget.

**Comment by RhomGit** [comment]
ping @rotorgames 

Hi Kirill, whats the chance we could please have a fix published? We can't release to the App Store in this state and the workaround is rather onerous. Also thanks @michaelstonis for your efforts thus far.

> 1.33 Binary Rejected 
> Sep 27, 2019 
> Guideline 2.1 - Performance - App Completeness Your app crashed on iPad running iOS 13.1 on WiFi when we: - Launched app - Tapped Sign in

**Comment by bo3po** [comment]
I have this issue also. Popup goes away. And the exception that everyone else gets. But not always. A log of times tough. I'll have to clone and apply the fix to release. Please fix this soon :)

**Comment by hoangwy** [comment]
Same here, Please fix this soon.
Thanks so much

**Comment by TGlev** [comment]
ping @rotorgames

**Comment by shnaz** [comment]
Same issue here. I would rather not clone this project, but it seems that there is no other way.

**Comment by MikeC2** [comment]
Wondering if @ysmoradi  or @pizzahead24 would be able to publish the fix?

**Comment by movisis** [comment]
> I figured out the issue. It has to do with how iOS 13 is managing the life of the `window` variable. To _resolve_ this for now, I just maintain a handle to the displayed windows, so that they do not automatically deallocated.
> 
> There are [similar reports](https://stackoverflow.com/questions/57060606/uiwindow-not-showing-over-content-in-ios-13) from other iOS developers with extremely similar or the same issue.
> 
> Attached is a nuget package that can be hosted on a local machine or in DevOps for the meantime for local consumption. Just remove the .zip extension after you download it.
> 
> I will send up a PR with this same resolution soon.
> 
> ```
> using System.Collections.Generic;
> using System.Linq;
> using System.Threading.Tasks;
> using CoreGraphics;
> using Foundation;
> using HealthKit;
> using Rg.Plugins.Popup.Contracts;
> using Rg.Plugins.Popup.IOS.Extensions;
> using Rg.Plugins.Popup.IOS.Impl;
> using Rg.Plugins.Popup.IOS.Platform;
> using Rg.Plugins.Popup.Pages;
> using UIKit;
> using Xamarin.Forms;
> using Xamarin.Forms.Platform.iOS;
> using XFPlatform = Xamarin.Forms.Platform.iOS.Platform;
> 
> [assembly: Dependency(typeof(PopupPlatformIos))]
> namespace Rg.Plugins.Popup.IOS.Impl
> {
>     [Preserve(AllMembers = true)]
>     internal class PopupPlatformIos : IPopupPlatform
>     {
>         private readonly List<UIWindow> _windows = new List<UIWindow>();
> 
>         private bool IsiOS9OrNewer => UIDevice.CurrentDevice.CheckSystemVersion(9, 0);
>         private bool IsiOS13OrNewer => UIDevice.CurrentDevice.CheckSystemVersion(13, 0);
> 
>         public event EventHandler OnInitialized
>         {
>             add => Popup.OnInitialized += value;
>             remove => Popup.OnInitialized -= value;
>         }
> 
>         public bool IsInitialized => Popup.IsInitialized;
> 
>         public bool IsSystemAnimationEnabled => true;
> 
>         public async Task AddAsync(PopupPage page)
>         {
>             page.Parent = Application.Current.MainPage;
> 
>             page.DescendantRemoved += HandleChildRemoved;
> 
>             if(UIApplication.SharedApplication.KeyWindow.WindowLevel == UIWindowLevel.Normal)
>                 UIApplication.SharedApplication.KeyWindow.WindowLevel = -1;
> 
>             var renderer = page.GetOrCreateRenderer();
> 
>             var window = new PopupWindow();
> 
>             if(IsiOS13OrNewer)
>             {
>                 _windows.Add(window);
>             }
> 
>             window.BackgroundColor = Color.Transparent.ToUIColor();
>             window.RootViewController = new PopupPlatformRenderer(renderer);
>             window.RootViewController.View.BackgroundColor = Color.Transparent.ToUIColor();
>             window.WindowLevel = UIWindowLevel.Normal;
>             window.MakeKeyAndVisible();
> 
>             if (!IsiOS9OrNewer)
>             {
>                 window.Frame = new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, UIScreen.MainScreen.Bounds.Height);
>             }
> 
>             await window.RootViewController.PresentViewControllerAsync(renderer.ViewController, false);
>         }
> 
>         public async Task RemoveAsync(PopupPage page)
>         {
>             var renderer = XFPlatform.GetRenderer(page);
>             var viewController = renderer?.ViewController;
> 
>             await Task.Delay(50);
> 
>             page.DescendantRemoved -= HandleChildRemoved;
> 
>             if (renderer != null && viewController != null && !viewController.IsBeingDismissed)
>             {
>                 var window = viewController.View.Window;
>                 await window.RootViewController.DismissViewControllerAsync(false);
>                 DisposeModelAndChildrenRenderers(page);
>                 window.RootViewController.Dispose();
>                 window.RootViewController = null;
>                 page.Parent = null;
>                 window.Hidden = true;
> 
>                 if(IsiOS13OrNewer && _windows.Contains(window))
>                 {
>                     _windows.Remove(window);
>                 }
> 
>                 window.Dispose();
>                 window = null;
> 
>                 if (UIApplication.SharedApplication.KeyWindow.WindowLevel == -1)
>                     UIApplication.SharedApplication.KeyWindow.WindowLevel = UIWindowLevel.Normal;
>             }
>         }
> 
>         private void DisposeModelAndChildrenRenderers(VisualElement view)
>         {
>             IVisualElementRenderer renderer;
>             foreach (VisualElement child in view.Descendants())
>             {
>                 renderer = XFPlatform.GetRenderer(child);
>                 XFPlatform.SetRenderer(child, null);
> 
>                 if (renderer != null)
>                 {
>                     renderer.NativeView.RemoveFromSuperview();
>                     renderer.Dispose();
>                 }
>             }
> 
>             renderer = XFPlatform.GetRenderer(view);
>             if (renderer != null)
>             {
>                 renderer.NativeView.RemoveFromSuperview();
>                 renderer.Dispose();
>             }
>             XFPlatform.SetRenderer(view, null);
>         }
> 
>         private void HandleChildRemoved(object sender, ElementEventArgs e)
>         {
>             var view = e.Element;
>             DisposeModelAndChildrenRenderers((VisualElement) view);
>         }
>     }
> }
> ```
> 
> [Rg.Plugins.Popup.1.1.5.189.nupkg.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/3650499/Rg.Plugins.Popup.1.1.5.189.nupkg.zip)

Yeah.. tested in iOS 12 and 13, and this worked fine.

**Comment by alextorres50** [comment]
> @mr5z You can use this source to test the changes made in the pr: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99
> 
> It should be the version 1.1.5.214

doesn't work with custom popupage the OnDisappearingAnimationEndAsync() is execute, but the background doesn't popup, i tried with popasync() and popupallasync() and the Task never finish...

**Comment by michaelstonis** [comment]
> > @mr5z You can use this source to test the changes made in the pr: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99
> > It should be the version 1.1.5.214
> 
> doesn't work with custom popupage the OnDisappearingAnimationEndAsync() is execute, but the background doesn't disappear, i tried with popasync() and popupallasync() and the Task never finish...

@alextorres50 can you post a minimal repro solution? I can look into if there is a straight-forward way to manage that.

**Comment by rotorgames** [comment]
Hi guys. I'm sorry for the long answering. Version 1.1.5.214 in Development Nuget Source (https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99) has to fix this issue. Actually, I fixed it 5 months ago. I wanted to add more features in the next release but I didn't have enough time for it. 

I will publish 1.1.5.214 in NuGet ASAP but you can use Development Nuget Source right now if you want.

**Comment by rotorgames** [comment]
Hi guys. I'm sorry for the long answering.

Can someone test v1.1.5.216 from Development Nuget with stable versions of VS4Mac, Xamarin.iOS and Xamarin.Forms? 

Please, let me know if v1.1.5.216 still have this issue.

**Comment by alextorres50** [comment]
> > > @mr5z You can use this source to test the changes made in the pr: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99
> > > It should be the version 1.1.5.214
> > 
> > 
> > doesn't work with custom popupage the OnDisappearingAnimationEndAsync() is execute, but the background doesn't disappear, i tried with popasync() and popupallasync() and the Task never finish...
> 
> @alextorres50 can you post a minimal repro solution? I can look into if there is a straight-forward way to manage that.

Due to privacy issues I cannot share the project where the error is presented,

but it is very simple

When you run a background task with high load command, in my case a banner with information, this information load into ObservableCollection, after the Popup closes leaves the user interaction invalid, as if the background did not disappear.

Try to replicate it in a separate project but the same did not happen.

Use the latest versions of Xamarin.Forms and others that were stable to rule out that, but not.

The XF versions that were tested were
 XF => 4.2.0.815419
XF => 3.6.0.264807
XF => 4.0.0.394984-pre10

**Comment by rotorgames** [comment]
@alextorres50 Could you try to test vv1.1.5.216 in your project?

**Comment by Bloodyairtimer** [comment]
I tried the  v1.1.5.216 package but popping items from the PopupStack seems to close the popup but not clearing the stack.

**Comment by alextorres50** [comment]
> @alextorres50 Could you try to test v1.1.5.216 in your project?

OK, v.1.1.5.216 fix partialty my error and I confirm that the use :

**First Method**
`
                    var root = new NavigationPage(new HomePage());
                    _navigationService.Initialize(root);
                    App.Current.MainPage = root;` 
to navigate or set to RootPage doesnt work fine on IOS 13, generate Issues to load image, data and content 

I change this to: 

**Second Method**
`_navigation.Navigation.InsertPageBefore(new HomePage(), _navigation.Navigation.NavigationStack[0]);
            await _navigation.Navigation.PopToRootAsync();`

where  _navigation is the initial NavigationPage.

Also confirmed that this fix work with: 

Iphone 11 IOs 13 simulator/
XF=> 3.6.0.264807

Failed to:
Iphone 8 IOs simulator
XF=> 4.2.0.709249, 3.6.0.264807

**Comment by rotorgames** [comment]
So, I have created a new build (1.1.5.220) in Dev nuget which contains this fix and some improvements. Could you test it and let me know? I'm going to publish a new release this week.

**Comment by Bloodyairtimer** [comment]
> So, I have created a new build (1.1.5.220) in Dev nuget which contains this fix and some improvements. Could you test it and let me know? I'm going to publish a new release this week.

Tested it and all issues are gone! Thanks!

**Comment by mindport** [comment]
Restoring packages for Xamarin.iOS,Version=v1.0...
  GET https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99/FindPackagesById()?id='Rg.Plugins.Popup'&semVerLevel=2.0.0
Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.

**Comment by rotorgames** [comment]
@mindport It's nuget or VS bug. I close VS and run `dotnet nuget locals all --clear` in a terminal. After it restoring works fine.

**Comment by mindport** [comment]
Sorry @rotorgames Maybe its a local problem for me but after your suggested terminal fix I get these errors.

Restoring packages for Xamarin.iOS,Version=v1.0...
  GET https://api.nuget.org/v3-flatcontainer/rg.plugins.popup/index.json
  GET https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99/FindPackagesById()?id='Rg.Plugins.Popup'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99/FindPackagesById()?id='Rg.Plugins.Popup'&semVerLevel=2.0.0'.
The SSL connection could not be established, see inner exception.
  Unable to write data to the transport connection: The socket is not connected.
  The socket is not connected
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/rg.plugins.popup/index.json'.
The SSL connection could not be established, see inner exception.
  Unable to write data to the transport connection: The socket is not connected.
  The socket is not connected
  GET https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99/FindPackagesById()?id='Rg.Plugins.Popup'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3-flatcontainer/rg.plugins.popup/index.json
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/rg.plugins.popup/index.json'.
The SSL connection could not be established, see inner exception.
  Unable to write data to the transport connection: The socket is not connected.
  The socket is not connected
Retrying 'FindPackagesByIdAsyncCore' for source 'https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99/FindPackagesById()?id='Rg.Plugins.Popup'&semVerLevel=2.0.0'.
The SSL connection could not be established, see inner exception.
  Unable to write data to the transport connection: The socket is not connected.
  The socket is not connected
  GET https://api.nuget.org/v3-flatcontainer/rg.plugins.popup/index.json
  GET https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99/FindPackagesById()?id='Rg.Plugins.Popup'&semVerLevel=2.0.0
Failed to retrieve information about 'Rg.Plugins.Popup' from remote source 'https://api.nuget.org/v3-flatcontainer/rg.plugins.popup/index.json'.

**Comment by rotorgames** [comment]
@mindport restart your mac

**Comment by mindport** [comment]
@rotorgames That worked like a charm, thanks :)

**Comment by rotorgames** [comment]
@mindport Nice to hear it. Let me know please about the last version in dev nuget.

**Comment by alextorres50** [comment]
@rotorgames  v.1.1.5.220 return the bug in my case

**Comment by rotorgames** [comment]
@alextorres50 Could you create a simple project which reproduces your issue and upload it on github?

**Comment by alextorres50** [comment]
> @alextorres50 Could you create a simple project which reproduces your issue and upload it on github?
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Rg.Plugins.Popup.IOS.Impl.PopupPlatformIos.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x000f0] in <800392c4741d4f63bfe0a8cddbb57bec>:0 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x00028] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:163 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass11_0.<RemovePageAsync>b__0 () [0x00168] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:136 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass16_0.<InvokeThreadSafe>b__0 () [0x00025] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:193 
  at Veryx.ViewModels.InitialSetup.LoginViewModel.<get_LoginCommand>b__26_0 (System.Object sender) [0x005a3] in /Users/user/VERyx-Mobile/Veryx/ViewModels/InitialSetup/LoginViewModel.cs:173 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Veryx.iOS.Application.Main (System.String[] args) [0x00001] in /Users/user/VERyx-Mobile/Veryx.iOS/Main.cs:17
2019-10-03 08:29:15.007309-0500 Veryx.iOS[1464:25904] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
  at Rg.Plugins.Popup.IOS.Impl.PopupPlatformIos.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x000f0] in <800392c4741d4f63bfe0a8cddbb57bec>:0 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x00028] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:163 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass11_0.<RemovePageAsync>b__0 () [0x00168] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:136 
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass16_0.<InvokeThreadSafe>b__0 () [0x00025] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:193 
  at Veryx.ViewModels.InitialSetup.LoginViewModel.<get_LoginCommand>b__26_0 (System.Object sender) [0x005a3] in /Users/user/VERyx-Mobile/Veryx/ViewModels/InitialSetup/LoginViewModel.cs:173 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Veryx.iOS.Application.Main (System.String[] args) [0x00001] in /Users/user/VERyx-Mobile/Veryx.iOS/Main.cs:17
MonoTouch: Could not install sigaction override, unexpected sigaction implementation.
```

This is the stacktrace

**Comment by rotorgames** [comment]
@alextorres50 What version of the plugin do you use?

**Comment by alextorres50** [comment]
> @alextorres50 What version of the plugin do you use?

v.1.1.5.116 stacktrace error, v.1.1.5.220 the background window or view that cancelled user interaction appearred again, but I see that suceded with async task, I go to home screen to IOs and return to the app, the app lost the freeze and  function again.
I try to search if issue is to xamarin forms

**Comment by rotorgames** [comment]
@alextorres50 I can't solve this issue if you don't create an example. It will be awesome if you create a simple project which can replicate your issue.

**Comment by gailgarciad** [comment]
Hi @rotorgames, Thank you so much for working on this!! 220 works fine for me and the popups does not close automatically, but I have some popups that contains editors field, and the application crashes when opening those popups. Any ideas on how to address this issue?
Thanks!!

**Comment by alextorres50** [comment]
> Hi @rotorgames, Thank you so much for working on this!! 220 works fine for me and the popups does not close automatically, but I have some popups that contains editors field, and the application crashes when opening those popups. Any ideas on how to address this issue?
> Thanks!!

If is a third party libraries you should wait the release of this libraries, because a lof of libraries don't prepared to IOs13, and update the dependency of this library doesn't fix the issue completily

**Comment by rotorgames** [comment]
@gailgarciad Could you give a stack-trace?

**Comment by oddfrer** [comment]
Thanks for the fix, @rotorgames! 220 works for our application. Could you perhaps add 220 as a pre-release to nuget.org?

**Comment by rotorgames** [comment]
@oddfrer I will publish a stable release in NuGet today.

**Comment by letrungdo** [comment]
@rotorgames version v.1.1.5.220 has an bug when rotating the device horizontally, vertically not fire OnSizeAllocated

**Comment by letrungdo** [comment]
Hi @rotorgames version v.1.1.5.223 has an bug on iOS 13 when rotating the device horizontally, vertically not fire OnSizeAllocated

**Comment by rotorgames** [comment]
Done

**Comment by bgarnica** [comment]
HI there,

I have an application using Xamarin.Forms 3.6.0.3444457 and Rs.Plugins.PopUp plugin with version 1.2.0.223. However I'm still getting an exception and application crashes when popup is closed using this (only in iOS):

`try
{
  await PopupNavigation.Instance.PopAsync(true);
}
catch(Exception exc)
{
  Console.Write(exc.Message);
}`

Exception is never catched and application ever crashes. Should I upgrade to Xamarin.Forms > 4.0 ? and a newer version for the plugin?

Thanks a lot.

**Comment by LuckyDucko** [comment]
We would recommend you upgrade yes and see if you still come up against issues

**Comment by gpticar-oa** [comment]
Hi

You should upgrade all packages to latest including xamarin.forms.
I have currently xf 4.8.0.1534 and rg.plugins.popup 2.0.0.6 and everything
is working fine.

Lp

*Goran Ptičar*
*Omni Aspect. d.o.o.*
A. Šenoe 2
44320 Kutina
tel: +385 (0)44 605 167
mob: +385 (0)99 4200 339
fax: +385 (0)44 605 172
e-mail: goran.pticar@omniaspect.hr <igor.ivanic@omniaspect.hr>
www.omniaspect.hr
<http://www.omniaspect.com/>



VAŽNO: Ova poruka elektroničke poste, kao i svi privici, može sadržavati
povjerljive i/ili zakonski povlaštene informacije koje su namijenjene
isključivo naznačenom(im) primatelju(ima). Ako ste ovu poruku primili
greškom, odmah obavijestite pošiljatelja, a poruku kao i sve njezine kopije
i privitke odmah i bez tiskanja, čitanja ili kopiranja trajno obrišite s
računalnog sustava. Osim primatelju, strogo je zabranjena svaka uporaba,
distribucija ili kopiranje ove poruke. Primatelj treba provjeriti ovu
poruku e-poste i sve privitke.

IMPORTANT: This e-mail, and any attachments, may contain confidential,
and/or legally privileged information, and is intended solely for the use
only of the named addressee(s). If you have received this e-mail in error,
please notify the sender immediately, and permanently delete the original
and any copies of this e-mail, and any attachments, without printing,
reading or copying them. Any use, distribution, or copying of this e-mail
other than by the intended recipient is strictly prohibited. The recipient
should check this e-mail and any attachments.


sri, 28. lis 2020. u 03:10 Brian Garnica <notifications@github.com> napisao
je:

**Comment by bgarnica** [comment]
HI there, 

I just upgraded Xamarin.Forms package to version 4.6.0.726 and Rg.Plugins.Popup version to latest. However, I'm still getting same issue.

I open a PopUp with:

           `....
           PopupDatosTransaccionPage popup = new PopupDatosTransaccionPage(objReto, "Escenarios");
            var scaleAnimation = new ScaleAnimation
            {
                PositionIn = MoveAnimationOptions.Right,
                PositionOut = MoveAnimationOptions.Left
            };

            popup.Animation = scaleAnimation;
            await PopupNavigation.Instance.PushAsync(popup);`

And within popup page I have a "Dismiss" button with:

            `try
            {
                await PopupNavigation.Instance.PopAllAsync(true);
            }
            catch (Exception exc)
            {
                Console.Write(exc.Message);
            }`

If I'm debugging, when Dimiss button is clicked; app crashes and debugger is finished. When I'm running my app using Simulator but without breakpoints and dismiss button is clicked, popup seems to close, but UI keeps blocked (like if a transparent layer is still present on screen)

Please, if i'm not so clear, just let me know.

**Comment by bgarnica** [comment]
> HI there,
> 
> I just upgraded Xamarin.Forms package to version 4.6.0.726 and Rg.Plugins.Popup version to latest. However, I'm still getting same issue.
> 
> I open a PopUp with:
> 
> ```
>        `....
>        PopupDatosTransaccionPage popup = new PopupDatosTransaccionPage(objReto, "Escenarios");
>         var scaleAnimation = new ScaleAnimation
>         {
>             PositionIn = MoveAnimationOptions.Right,
>             PositionOut = MoveAnimationOptions.Left
>         };
> 
>         popup.Animation = scaleAnimation;
>         await PopupNavigation.Instance.PushAsync(popup);`
> ```
> 
> And within popup page I have a "Dismiss" button with:
> 
> ```
>         `try
>         {
>             await PopupNavigation.Instance.PopAllAsync(true);
>         }
>         catch (Exception exc)
>         {
>             Console.Write(exc.Message);
>         }`
> ```
> 
> If I'm debugging, when Dimiss button is clicked; app crashes and debugger is finished. When I'm running my app using Simulator but without breakpoints and dismiss button is clicked, popup seems to close, but UI keeps blocked (like if a transparent layer is still present on screen)
> 
> Please, if i'm not so clear, just let me know.

I forgot to mention I'm trying to use iOS Simulator: iPhone 11, iOS 13.4
