### ISSUE TITLE
sometimes popup doesn't close well

### ISSUE THREAD

**Issue by arifinWM** [rotorgames/Rg.Plugins.Popup#87]
Hi rotorgames,

I'm using below environment
xamarin forms version: 2.3.3.180
rg pop up version: 1.0.4

I'm using this pop up to show loading page.
I'm creating 1 page inherited to PopupPage.
Please find below code.

```
public partial class LoadingPopupPage : PopupPage
    {        
        public LoadingPopupPage()
        {
            ActivityIndicator indicator = new ActivityIndicator
            {
                Color = Color.White,
                IsRunning = true,
                IsEnabled = true,
                VerticalOptions = LayoutOptions.Center,
                HorizontalOptions = LayoutOptions.Center,
                HeightRequest = 70,
                WidthRequest = 70
            };
            var popupframe = new Frame
            {
                Padding = new Thickness (1.0)                   
            };
            var popupstacklayout = new StackLayout
            {
                Children =
                {
                    indicator,
                    new Label
                    {
                        Text = "Please Wait",
                        TextColor = Color.White
                    }
                }
            };
            popupstacklayout.VerticalOptions = LayoutOptions.Center;
            popupstacklayout.HorizontalOptions = LayoutOptions.Center;            
            popupstacklayout.Padding = new Thickness(40, 20);
                                    
            Content = popupstacklayout;            
        }

        public async void closepupup()
        {            await Navigation.PopPopupAsync();
            await Navigation.RemovePopupPageAsync(this);
        }

```

I called this page from my webview page.

```
private void webview_navigated(object sender, WebNavigatedEventArgs e)
        {            
            webloadingpage.closepupup();         
        }

        private async void webview_navigating(object sender, WebNavigatingEventArgs e)
        {            
            webloadingpage = new LoadingPopupPage();
            await Navigation.PushPopupAsync(webloadingpage);

        }
```

Sometimes when it hits the webview_navigated (I debug and it hits the webloadingpage.closepopup() line), the close popup process could not close the popup well. Please advise

Best Regards,
Afin

**Comment by rotorgames** [comment]
@arifinWM Hi. Can you show stacktrace or can you get your project to me?

**Comment by EmilAlipiev** [comment]
I experience similar issue. popup is not closing sometimes. It is hard to identify what exact problem is because for the same code for me, sometimes, it works, sometimes it doesnt. I have feeling that if my code executes fast. it doesnt close. anyway I will update this if i find something more, just a quick question. do we really need to use RemovePopupPageAsync() when we use PopPopupAsync(). In which case we need RemovePopupPageAsync()?

**Comment by rotorgames** [comment]
@EmilAlipiev Are you sure that you closed the popup page which was opened? 'webview_navigating' could be invoked repeatedly. Then the 'webloadingpage' could be changed and you could close the other page. I recommend to use the 'RemovePopupPageAsync' only if you want to close page in center of the 'PopupStack'. 

'PopPopupAsync' will close last page in the 'PopupStack' if it contains any pages. 

'RemovePopupPageAsunc' will close a page which you will add in the first parameter.

**Comment by arifinWM** [comment]
Hi @rotorgames ,

Do you have private email ?
I'll send the sample code to your email directly.

Thanks

Best Regards,
Afin

**Comment by rotorgames** [comment]
@arifinWM Write your email here. I will send empty letter to you.

**Comment by arifinWM** [comment]
Hi @rotorgames ,

arifin_wm@hotmail.com

Thanks

Best Regards,
Afin

**Comment by EmilAlipiev** [comment]
hey guys, 
I fixed my problem. i was my coding mistake. PopPopupAsync works just fine for me. cheers

**Comment by arifinWM** [comment]
Hi @rotorgames ,

I'm using below code

            await Navigation.PushPopupAsync(campaignlistloading);
            RefreshData();
            await Navigation.RemovePopupPageAsync(campaignlistloading);

and so far it's worked. I'm trying to figure it out again using any case.

Thanks

Best REgards,
Afin

**Comment by rotorgames** [comment]
@arifinWM Is `RefreshData` async methods? What do you do in it? 

Try to add `Task.Delay(200)` between `RefreshData` and `await Navigation.RemovePopupPageAsync(campaignlistloading);`. If it work, please will notify me about it.

**Comment by arifinWM** [comment]
refreshData is sync method.
It's only refresh the view with the newest data.

I've added the delay as Your's suggestion and it worked.
Thanks for your advise :)

**Comment by rotorgames** [comment]
@arifinWM What devices (OS) had this problem?

**Comment by kalpeshah** [comment]
Hello,

I have problem similar to ArifinWM. 

await Navigation.PushPopupAsync(campaignlistloading);
RefreshData();
await Navigation.RemovePopupPageAsync(campaignlistloading);

After debugging, i could conclude that many times PushPopupAsync does not return for long. And hence RemovePopupPage gets called even before PushPopupAsync completes its work.

Adding 200 ms delay as you have suggested works. I have been testing on simulator and an android tablet.

But by reducing the delay to 10 ms, it does not work.

So my question is what is your reasoning behind 200 ms ? Can you please explain ? Someday if the device is busy, may be even 200 ms may not work. Can we please have more stable solution. Adding delay is not definitely something i would like to work. 

Can you please help ?

Thanks

-Kalpesh

**Comment by arifinWM** [comment]
Hi @rotorgames ,

I test on below OS:
- iOS 10.1
- iOS 8.4
- iOS 9.3.5
- iOS 10.2.1
in different device (iPad 2, iphone 5s, iphone 7, ipad mini)

Best REgards,
Afin

**Comment by arifinWM** [comment]
Hi @kalpeshah ,

**Comment by arifinWM** [comment]
Hi @kalpeshah ,

it seems that async method is the issue.
and the parameter 200 seem that delay time of async method call from previous call, but I agree that it seems different on different device and process. It could be 500 at the next time and it looks unstable.

Hi @rotorgames ,

Please advise, I'm sorry I'm reopening the case.

Best Regards,
Afin

**Comment by rotorgames** [comment]
@kalpeshah Please wait. I will fix this problem.

@arifinWM Is this problem only on iOS?

**Comment by arifinWM** [comment]
Hi @rotorgames ,

I haven't yet deployed on Android since my implementation wave 1 will be on iOS.
Next wave on Android will be next month.

Best Regards,
Afin

**Comment by rotorgames** [comment]
This issue was fixed in v1.1.0-pre1. Please test it and tell me about your tests. Thank you.

**Comment by kalpeshah** [comment]
Ok thanks. I will test it.

Kalpesh Shah
Director, Vaagha Consultancy Ltd
Contact : 0044-7743391227


________________________________

**Comment by healthendeavorsbp** [comment]
This problem still exists. Can reproduce consistently on android emulator api 27 with pixel.
Adding the delay resolved the problem, but was very hard to track down.
